/* ================================================================
   Delivery & PMO — Agent Tower registry
   ================================================================ */

import type {
  AgentDecision,
  AgentRegistry,
  AgentSpec,
  DecisionTrace,
} from "@/components/agents/types";

const AGENTS: AgentSpec[] = [
  {
    id: "status_drafter",
    name: "Status Drafter",
    purpose: "Drafts weekly status across audiences (exec, sponsor, customer) from real project data.",
    description:
      "Synthesises a one-pager for execs, a sponsor email, and a customer-facing portal note every Friday. Pulls from completed work, slipping tasks, recent comments, and risk items — never re-reports what humans already wrote. Tone is matched to audience.",
    trigger: "scheduled",
    triggerDetail: "Every Friday 16:00 (per-project timezone)",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "brand",
    iconName: "FileText",
    activity7d: [3, 0, 0, 0, 0, 12, 0],
    accuracy30d: 0.91,
    overrideRate30d: 0.09,
    kpis: [
      { label: "PM hours saved / project / wk", value: "2.4 h", hint: "Median across 18 active projects", trend: "up" },
      { label: "Status acceptance rate",         value: "84%",   hint: "Drafts accepted without edit",      trend: "up" },
    ],
    recentActions: [
      { id: "ra-sd-1", when: "12m ago",   text: "Drafted 12 exec one-pagers; 9 accepted, 3 edited." },
      { id: "ra-sd-2", when: "1h ago",    text: "Sponsor email for Phoenix Migration sent for approval." },
      { id: "ra-sd-3", when: "Yesterday", text: "Customer portal note for Acme Bank refreshed (no negative items hidden)." },
    ],
    requiredPermissions: ["delivery.project.read", "delivery.task.read"],
  },
  {
    id: "risk_sentinel",
    name: "Risk Sentinel",
    purpose: "Watches slipping tasks, sentiment, dependencies, capacity → opens risks with reasoning.",
    description:
      "Continuous scan: schedule slippage, comment sentiment, broken cross-project dependencies, capacity squeeze, sprint-velocity drop. Doesn't just throw alerts — opens a risk item with severity, root-cause reasoning, and recommended mitigations.",
    trigger: "continuous",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "warning",
    iconName: "TriangleAlert",
    activity7d: [8, 6, 11, 5, 9, 2, 4],
    accuracy30d: 0.82,
    overrideRate30d: 0.18,
    kpis: [
      { label: "Risks raised before slip",       value: "73%",   hint: "Caught >7 days before the milestone breach", trend: "up" },
      { label: "Materialised risk rate",          value: "61%",   hint: "Of raised risks that became real issues",     trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-rs-1", when: "8m ago",    text: "Opened HIGH risk on Phoenix Migration: 3 critical-path tasks slipping." },
      { id: "ra-rs-2", when: "1h ago",    text: "Detected sentiment dip on Acme Bank's last 4 standup notes." },
      { id: "ra-rs-3", when: "3h ago",    text: "Capacity squeeze: Anil Sharma over-allocated W22 (140%)." },
    ],
    requiredPermissions: ["delivery.task.read", "delivery.sprint.read", "delivery.capacity.read"],
  },
  {
    id: "estimation_coach",
    name: "Estimation Coach",
    purpose: "Compares new estimates to historical analogues; surfaces overrun probability.",
    description:
      "When an engineer enters a new estimate, finds historically similar work, computes overrun probability, and suggests a range. Doesn't override the human — just shows the evidence. Feeds back into accuracy training.",
    trigger: "on_event",
    triggerDetail: "On new estimate entered",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "brand-teal",
    iconName: "Gauge",
    activity7d: [18, 22, 14, 19, 24, 6, 11],
    accuracy30d: 0.88,
    overrideRate30d: 0.12,
    kpis: [
      { label: "Estimate accuracy gain",          value: "+18%", hint: "Compared to 90 days ago",        trend: "up" },
      { label: "Median overrun reduction",        value: "−27%", hint: "Across last 6 sprint closes",     trend: "up" },
    ],
    recentActions: [
      { id: "ra-ec-1", when: "5m ago",   text: "Suggested 8–13d range for 'OAuth migration' (entered: 5d)." },
      { id: "ra-ec-2", when: "45m ago",  text: "Flagged 92% overrun probability on 'payments retry queue'." },
      { id: "ra-ec-3", when: "Yesterday",text: "Confirmed 2-week 'index rebuild' estimate vs 11 analogues." },
    ],
  },
  {
    id: "scope_creep_watcher",
    name: "Scope Creep Watcher",
    purpose: "Compares new tasks to original charter; flags drift; quantifies cost/time impact.",
    description:
      "Watches every new task and scope change against the project charter. When drift exceeds a threshold (default: 15% scope expansion or 10% cost), opens a scope-creep alert with quantified impact and asks for a charter update or change request.",
    trigger: "on_event",
    triggerDetail: "On task added or scope edited",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "destructive",
    iconName: "TrendingUp",
    activity7d: [2, 1, 3, 1, 4, 0, 2],
    accuracy30d: 0.79,
    overrideRate30d: 0.21,
    kpis: [
      { label: "Projects with controlled scope",  value: "68%",  hint: "Met charter without unapproved drift", trend: "up" },
      { label: "Avg drift caught early",          value: "11%",  hint: "Detected at this drift %; before, was 24%", trend: "up" },
    ],
    recentActions: [
      { id: "ra-sc-1", when: "20m ago",   text: "Flagged 22% scope drift on Acme Bank Phase 2 (3 new compliance tasks)." },
      { id: "ra-sc-2", when: "2h ago",    text: "Confirmed 'mobile responsive' was always in charter (no drift)." },
      { id: "ra-sc-3", when: "Yesterday", text: "Drafted change-request memo for Phoenix scope addition." },
    ],
  },
  {
    id: "standup_synthesiser",
    name: "Standup Synthesiser",
    purpose: "Pulls updates from chat, tools, async forms → clean digest with blockers + decisions.",
    description:
      "Replaces the daily live standup for distributed teams. Pulls async updates from Slack/Teams threads, PR activity, ticket transitions, and async standup forms. Produces a clean digest with blockers, decisions needed, and yesterday/today/risks per person.",
    trigger: "scheduled",
    triggerDetail: "Every weekday 09:15 local",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "brand-purple",
    iconName: "MessagesSquare",
    activity7d: [24, 24, 24, 24, 24, 0, 0],
    accuracy30d: 0.94,
    overrideRate30d: 0.06,
    kpis: [
      { label: "Standup time reduced",            value: "−42%",  hint: "Median over 6 weeks; replaced by digest", trend: "up" },
      { label: "Participation",                    value: "96%",   hint: "Of team submitted async update",          trend: "up" },
    ],
    recentActions: [
      { id: "ra-ss-1", when: "Today 9:15",  text: "Digest sent for 24 teams; 3 surfaced 'blocked' status." },
      { id: "ra-ss-2", when: "Yesterday",   text: "Highlighted decision needed on Acme Bank caching strategy." },
      { id: "ra-ss-3", when: "Yesterday",   text: "Caught implicit blocker chain across Phoenix → DataMesh." },
    ],
  },
  {
    id: "meeting_summariser",
    name: "Meeting Summariser",
    purpose: "Transcript → action items, decisions, risks; auto-assigns owners.",
    description:
      "Listens to every recorded meeting (Zoom/Meet/Teams). Produces structured output: action items (with owner + due), decisions made, risks raised, and follow-up topics. Auto-creates tasks in the project. Owner is inferred from speaker + context.",
    trigger: "on_event",
    triggerDetail: "After every meeting (when transcript posted)",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "brand",
    iconName: "Captions",
    activity7d: [12, 9, 14, 11, 8, 1, 0],
    accuracy30d: 0.86,
    overrideRate30d: 0.14,
    kpis: [
      { label: "Meetings with captured actions",  value: "91%",   hint: "Up from 38% pre-agent",  trend: "up" },
      { label: "Action items auto-assigned",      value: "183",    hint: "This week; 7% reassigned by humans", trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-ms-1", when: "15m ago",  text: "Summarised Phoenix steering committee; 6 action items, 2 decisions." },
      { id: "ra-ms-2", when: "1h ago",   text: "Caught a decision in 'Architecture sync' that wasn't called out." },
      { id: "ra-ms-3", when: "Yesterday",text: "Detected a risk in Acme Bank vendor call; opened risk item for review." },
    ],
  },
  {
    id: "dependency_tracker",
    name: "Dependency Tracker",
    purpose: "Notices cross-project dependencies forming implicitly; makes them explicit.",
    description:
      "Watches for shared people, shared components, and conversational mentions across projects. When two projects look implicitly coupled, opens a dependency item and notifies both PMs. Alerts on breakage when one side slips.",
    trigger: "continuous",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "warning",
    iconName: "Link",
    activity7d: [4, 3, 6, 2, 5, 1, 2],
    accuracy30d: 0.81,
    overrideRate30d: 0.19,
    kpis: [
      { label: "Surprise dependency incidents",   value: "−63%",  hint: "Over last quarter", trend: "up" },
      { label: "Implicit deps made explicit",     value: "47",    hint: "Last 30 days",       trend: "up" },
    ],
    recentActions: [
      { id: "ra-dt-1", when: "30m ago",   text: "Linked Acme Bank and Phoenix via shared service 'auth-svc'." },
      { id: "ra-dt-2", when: "4h ago",    text: "Detected Anil Sharma is critical-path on 3 projects this sprint." },
      { id: "ra-dt-3", when: "Yesterday", text: "Alerted on broken 'DataMesh ready' dep — Phoenix M2 at risk." },
    ],
  },
  {
    id: "capacity_forecaster",
    name: "Capacity Forecaster",
    purpose: "Forecasts capacity gaps 4–12 weeks out; suggests hires or reallocations.",
    description:
      "Joins approved leave (HR module), pipeline projects (CRM module), and open hires (Talent module). Produces capacity gap forecast per skill, per team, 4–12 weeks ahead. Recommends backfills, contractors, or reallocations.",
    trigger: "scheduled",
    triggerDetail: "Weekly + on-demand",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_teams"] },
    tone: "brand-teal",
    iconName: "BarChart3",
    activity7d: [1, 0, 0, 0, 1, 0, 0],
    accuracy30d: 0.84,
    overrideRate30d: 0.16,
    kpis: [
      { label: "Lead time on capacity decisions", value: "+19 d", hint: "More notice than before",  trend: "up" },
      { label: "Forecasted gaps filled",          value: "78%",   hint: "Closed before they hit",   trend: "up" },
    ],
    recentActions: [
      { id: "ra-cf-1", when: "Today",     text: "Forecast: 2.3 FTE backend gap in W28 (post-Anil leave + Phoenix Phase 2)." },
      { id: "ra-cf-2", when: "Yesterday", text: "Recommended starting 2 backend reqs (pipeline >70% commit)." },
      { id: "ra-cf-3", when: "3d ago",    text: "Suggested reallocating Sneha to bridge the W30 gap." },
    ],
    requiredPermissions: ["delivery.capacity.read", "leave.calendar.view.org", "talent.req.read"],
  },
  {
    id: "resource_conflict_resolver",
    name: "Resource Conflict Resolver",
    purpose: "Detects over-allocation; proposes alternatives matched on skills.",
    description:
      "When an allocation attempt would push a person past 100% in a sprint, finds skill-equivalent alternatives, ranks by availability + cost + skill-match, and suggests one. Flags critical-skill bottlenecks (only one person can do X).",
    trigger: "on_event",
    triggerDetail: "On allocation attempted",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_teams"] },
    tone: "brand-purple",
    iconName: "Shuffle",
    activity7d: [9, 11, 6, 8, 12, 1, 3],
    accuracy30d: 0.87,
    overrideRate30d: 0.13,
    kpis: [
      { label: "Conflicts auto-resolved",         value: "64%",   hint: "Suggestion accepted unedited", trend: "up" },
      { label: "Critical-skill bottlenecks",      value: "4 open", hint: "Tracked across active teams",  trend: "down" },
    ],
    recentActions: [
      { id: "ra-rc-1", when: "8m ago",    text: "Resolved Anil → Sneha for Phoenix Sprint 14 (skill match 91%)." },
      { id: "ra-rc-2", when: "1h ago",    text: "Flagged 'only Rajiv knows payments-2' as a critical-skill bottleneck." },
      { id: "ra-rc-3", when: "Yesterday", text: "Proposed contractor pool for DataMesh ETL workload." },
    ],
    requiredPermissions: ["delivery.capacity.write"],
  },
  {
    id: "health_scorer",
    name: "Health Scorer",
    purpose: "Composite health from schedule, budget, scope, team, customer signals.",
    description:
      "Computes a 0–100 health score per project from schedule adherence, budget burn, scope drift, team sentiment, and customer signals. Flags trend changes before the colour-coded RAG label flips — so PMs hear about an amber-leaning-red project before it visibly turns red.",
    trigger: "continuous",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "success",
    iconName: "Activity",
    activity7d: [24, 24, 24, 24, 24, 24, 24],
    accuracy30d: 0.89,
    overrideRate30d: 0.11,
    kpis: [
      { label: "Predictive lead on red flips",    value: "+11 d", hint: "Caught trending-red before RAG flipped", trend: "up" },
      { label: "Projects currently red",          value: "2 / 18",hint: "Down from 5 last month", trend: "up" },
    ],
    recentActions: [
      { id: "ra-hs-1", when: "Continuous", text: "Phoenix Migration dropped 78 → 64; flagged amber-leaning-red." },
      { id: "ra-hs-2", when: "1h ago",     text: "Acme Bank Phase 2 recovered 71 → 82 after staffing decision." },
      { id: "ra-hs-3", when: "Yesterday",  text: "DataMesh stable at 88 — sentiment improving." },
    ],
  },
  {
    id: "customer_update_composer",
    name: "Customer Update Composer",
    purpose: "Drafts customer-friendly milestone updates in the right tone.",
    description:
      "On milestone events (or sponsor request), drafts a customer-facing update. Concise, no internal jargon, no acknowledgement of internal noise. Optionally tonally tuned (formal vs friendly) per account.",
    trigger: "on_event",
    triggerDetail: "On milestone events",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["customer_facing_projects"] },
    tone: "brand-teal",
    iconName: "MessageCircle",
    activity7d: [2, 1, 3, 2, 1, 0, 1],
    accuracy30d: 0.92,
    overrideRate30d: 0.08,
    kpis: [
      { label: "Customer comms NPS",              value: "+12",   hint: "Vs pre-agent baseline", trend: "up" },
      { label: "Drafts accepted unedited",        value: "71%",   hint: "Across last 30 drafts", trend: "up" },
    ],
    recentActions: [
      { id: "ra-cu-1", when: "1h ago",    text: "Drafted Acme Bank Phase 2 milestone update (concise tone)." },
      { id: "ra-cu-2", when: "Yesterday", text: "Drafted Phoenix slipping-but-recovering note (transparent tone)." },
      { id: "ra-cu-3", when: "3d ago",    text: "Composed go-live celebration note for Lumen launch." },
    ],
  },
  {
    id: "decision_coach",
    name: "Decision Coach",
    purpose: "Surfaces analogous past decisions; prompts for reversibility, owner, success criteria.",
    description:
      "When a decision is being captured, finds analogous past decisions (with outcomes), and prompts the PM for missing structure: reversibility (one-way / two-way door), owner, success criteria, review date. Lifts decision documentation quality.",
    trigger: "on_event",
    triggerDetail: "On decision draft",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "brand-purple",
    iconName: "Lightbulb",
    activity7d: [5, 3, 6, 2, 4, 1, 2],
    accuracy30d: 0.83,
    overrideRate30d: 0.17,
    kpis: [
      { label: "Decisions with quality fields",   value: "88%",   hint: "Up from 31% pre-agent",     trend: "up" },
      { label: "Decisions reviewed at due date",  value: "62%",   hint: "Owner / success / review",  trend: "up" },
    ],
    recentActions: [
      { id: "ra-dc-1", when: "1h ago",    text: "Prompted owner+criteria on Acme Bank caching decision." },
      { id: "ra-dc-2", when: "Yesterday", text: "Surfaced 3 analogous decisions for the auth-svc rewrite call." },
      { id: "ra-dc-3", when: "3d ago",    text: "Flagged Phoenix 'pause vendor X' as one-way door (missing review date)." },
    ],
  },
  {
    id: "lessons_synthesiser",
    name: "Lessons Synthesiser",
    purpose: "Extracts retro patterns; surfaces relevant lessons when new similar projects start.",
    description:
      "Reads every retro across every project. Clusters recurring themes. When a new project is created with similar shape (e.g. data migration), surfaces the top 3–5 lessons most likely to apply — at the right time, not buried in a wiki.",
    trigger: "on_event",
    triggerDetail: "On project close + retros + new project start",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "brand-teal",
    iconName: "Library",
    activity7d: [1, 0, 2, 0, 1, 0, 0],
    accuracy30d: 0.86,
    overrideRate30d: 0.14,
    kpis: [
      { label: "Recurrence of known issues",      value: "−39%",  hint: "Issues seen in retros recurring", trend: "up" },
      { label: "Lessons surfaced per new project",value: "4.2",   hint: "Median; cap 8",                  trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-ls-1", when: "1d ago",    text: "Surfaced 5 migration-project lessons on DataMesh kickoff." },
      { id: "ra-ls-2", when: "1w ago",    text: "Clustered 12 'undersized infra' retros into a cross-cutting theme." },
      { id: "ra-ls-3", when: "2w ago",    text: "Published cross-portfolio theme: 'late vendor onboarding' (8 retros)." },
    ],
  },
  {
    id: "compliance_gate",
    name: "Compliance & Quality Gate",
    purpose: "Checks evidence at stage gates; blocks transitions missing artifacts.",
    description:
      "Sits on every stage-gate transition (kickoff → design → build → test → launch → close). Verifies required artifacts are present (charter signed, design reviewed, test plan attached). Blocks the transition if anything's missing.",
    trigger: "on_event",
    triggerDetail: "On gate transition attempt",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_projects"] },
    tone: "destructive",
    iconName: "ShieldCheck",
    activity7d: [1, 2, 0, 1, 3, 0, 0],
    accuracy30d: 0.98,
    overrideRate30d: 0.02,
    kpis: [
      { label: "Audit pass rate",                  value: "100%", hint: "Past 12 months",         trend: "up" },
      { label: "Blocked transitions resolved",     value: "94%",  hint: "Within 48h of block",    trend: "up" },
    ],
    recentActions: [
      { id: "ra-cg-1", when: "2h ago",    text: "Blocked Phoenix Design → Build (missing security review)." },
      { id: "ra-cg-2", when: "Yesterday", text: "Approved Acme Bank Build → Test (all artifacts present)." },
      { id: "ra-cg-3", when: "3d ago",    text: "Blocked Lumen Launch → Close (no signed customer acceptance)." },
    ],
  },
  {
    id: "pmo_coach",
    name: "PMO Coach",
    purpose: "Coaches new PMs on methodology, templates, anti-patterns.",
    description:
      "Pairs with new PMs and surfaces healthy patterns. Flags anti-patterns: 30 critical-path tasks all owned by one person; no risk items 4 weeks in; no retros logged; missing acceptance criteria. Coaches rather than blocks.",
    trigger: "continuous",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["new_pms"] },
    tone: "warning",
    iconName: "GraduationCap",
    activity7d: [3, 2, 4, 1, 5, 0, 1],
    accuracy30d: 0.81,
    overrideRate30d: 0.19,
    kpis: [
      { label: "New PM ramp time",                 value: "−32%", hint: "Time-to-first-healthy-project", trend: "up" },
      { label: "Anti-patterns surfaced this wk",  value: "11",    hint: "Across new-PM cohort",          trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-pc-1", when: "1h ago",    text: "Nudged Aisha (new PM) — 18 of 22 critical-path tasks on one person." },
      { id: "ra-pc-2", when: "Yesterday", text: "Coached Vikram on running a healthy first retro." },
      { id: "ra-pc-3", when: "3d ago",    text: "Suggested risk-review cadence to 2 new PMs (4 weeks in, no risks logged)." },
    ],
  },
];

const DECISIONS: AgentDecision[] = [
  { id: "dd-1",  agentId: "risk_sentinel",        whenISO: "2026-05-11T11:22:00", whenLabel: "8m ago",    summary: "Opened HIGH risk: Phoenix Migration — 3 critical-path tasks slipping >2 days.", outcome: "suggested",  confidence: 87, recordId: "p-phoenix",  recordLabel: "Phoenix Migration" },
  { id: "dd-2",  agentId: "estimation_coach",     whenISO: "2026-05-11T11:25:00", whenLabel: "5m ago",    summary: "Suggested 8–13d range for 'OAuth migration' (engineer entered: 5d).",          outcome: "suggested",  confidence: 92, recordId: "t-oauth",     recordLabel: "OAuth migration" },
  { id: "dd-3",  agentId: "compliance_gate",      whenISO: "2026-05-11T09:30:00", whenLabel: "2h ago",    summary: "Blocked Phoenix Design → Build transition: security review missing.",          outcome: "executed",   confidence: 100, recordId: "p-phoenix",  recordLabel: "Phoenix Migration" },
  { id: "dd-4",  agentId: "status_drafter",       whenISO: "2026-05-11T11:18:00", whenLabel: "12m ago",   summary: "Drafted 12 exec one-pagers for Friday status; 9 accepted, 3 pending review.", outcome: "pending_review", confidence: 84 },
  { id: "dd-5",  agentId: "dependency_tracker",   whenISO: "2026-05-11T11:00:00", whenLabel: "30m ago",   summary: "Linked Acme Bank and Phoenix via implicit 'auth-svc' dependency.",             outcome: "suggested",   confidence: 81, recordId: "p-acme",      recordLabel: "Acme Bank Phase 2" },
  { id: "dd-6",  agentId: "capacity_forecaster",  whenISO: "2026-05-11T07:00:00", whenLabel: "Today",     summary: "Forecast 2.3 FTE backend gap W28 — recommended starting 2 reqs now.",          outcome: "suggested",   confidence: 79 },
  { id: "dd-7",  agentId: "resource_conflict_resolver", whenISO: "2026-05-11T11:22:00", whenLabel: "8m ago", summary: "Replaced Anil → Sneha for Phoenix Sprint 14 (skill match 91%, confirmed).",  outcome: "executed",    confidence: 91, recordId: "s-phoenix-14", recordLabel: "Phoenix Sprint 14" },
  { id: "dd-8",  agentId: "scope_creep_watcher",  whenISO: "2026-05-11T11:10:00", whenLabel: "20m ago",    summary: "Flagged 22% scope drift on Acme Bank Phase 2 (3 new compliance tasks).",        outcome: "suggested",  confidence: 78, recordId: "p-acme",      recordLabel: "Acme Bank Phase 2" },
  { id: "dd-9",  agentId: "standup_synthesiser",  whenISO: "2026-05-11T09:15:00", whenLabel: "Today 9:15", summary: "Async standup digest sent to 24 teams; 3 surfaced 'blocked' status.",            outcome: "executed",    confidence: 95 },
  { id: "dd-10", agentId: "meeting_summariser",   whenISO: "2026-05-11T11:15:00", whenLabel: "15m ago",    summary: "Captured Phoenix steering committee: 6 actions, 2 decisions, 1 risk.",           outcome: "executed",    confidence: 88 },
  { id: "dd-11", agentId: "health_scorer",        whenISO: "2026-05-11T11:30:00", whenLabel: "Just now",   summary: "Phoenix Migration health 78 → 64. Flagged amber-leaning-red.",                  outcome: "executed",    confidence: 89, recordId: "p-phoenix",  recordLabel: "Phoenix Migration" },
  { id: "dd-12", agentId: "customer_update_composer", whenISO: "2026-05-11T10:30:00", whenLabel: "1h ago", summary: "Drafted Acme Bank milestone update (concise tone) — awaiting Sponsor.",          outcome: "pending_review", confidence: 92, recordId: "p-acme",   recordLabel: "Acme Bank Phase 2" },
  { id: "dd-13", agentId: "decision_coach",       whenISO: "2026-05-11T10:33:00", whenLabel: "1h ago",     summary: "Prompted owner + success criteria on Acme caching decision.",                   outcome: "suggested",   confidence: 83 },
  { id: "dd-14", agentId: "lessons_synthesiser",  whenISO: "2026-05-10T15:00:00", whenLabel: "1d ago",     summary: "Surfaced 5 migration-project lessons on DataMesh kickoff.",                     outcome: "suggested",   confidence: 86, recordId: "p-datamesh", recordLabel: "DataMesh" },
  { id: "dd-15", agentId: "pmo_coach",            whenISO: "2026-05-11T10:30:00", whenLabel: "1h ago",     summary: "Nudged Aisha — 18 of 22 critical-path tasks on a single person.",               outcome: "suggested",   confidence: 84 },
];

const TRACES: Record<string, DecisionTrace> = {
  "dd-1": {
    decisionId: "dd-1",
    input: [
      { label: "Project",      value: "Phoenix Migration (p-phoenix)" },
      { label: "Window",       value: "Last 7 days" },
      { label: "Signal types", value: "schedule_slip, comment_sentiment, dep_break, capacity" },
    ],
    tools: [
      { id: "t1", name: "Task slip scan",         whenLabel: "11:21:42", summary: "Computed schedule variance for every open task.", kind: "data_fetch",  result: "{ slipping: 3, critical_path: true, slip_avg_days: 2.4 }" },
      { id: "t2", name: "Sentiment model call",   whenLabel: "11:21:48", summary: "Scored sentiment on the 20 most recent comments.", kind: "model_call", result: "{ trend: 'down', score: -0.31 }" },
      { id: "t3", name: "Dependency graph check", whenLabel: "11:21:53", summary: "Checked downstream impact of slipping tasks.",     kind: "data_fetch",  result: "{ downstream_blocked: 4 }" },
      { id: "t4", name: "Capacity check",         whenLabel: "11:21:58", summary: "Read team allocation for the next 2 weeks.",       kind: "data_fetch",  result: "{ over_allocated: 1, name: 'Anil Sharma' }" },
    ],
    policyRules: [
      { id: "r1", label: "Critical-path tasks slipping ≥2d → HIGH",   outcome: "fail" },
      { id: "r2", label: "Sentiment trend > 30% negative → contribute", outcome: "warn" },
      { id: "r3", label: "Open dependencies on slipping tasks → contribute", outcome: "warn" },
    ],
    reasoning: [
      "3 critical-path tasks slipping >2 days each.",
      "Comment sentiment trending down across the last week.",
      "Anil Sharma over-allocated W22, blocking pickup of slipped work.",
      "Severity HIGH per policy threshold; mitigation = capacity rebalance.",
    ],
    output: {
      severity: "HIGH",
      mitigation: "Rebalance W22 capacity; rotate Sneha onto critical path.",
      raisedAt: "2026-05-11T11:22:00",
    },
  },
  "dd-3": {
    decisionId: "dd-3",
    input: [
      { label: "Transition", value: "Design → Build (Phoenix)" },
      { label: "Required",   value: "Charter signed, Design reviewed, Security review, Test plan" },
    ],
    tools: [
      { id: "t1", name: "Artifact registry scan", whenLabel: "09:29:11", summary: "Checked artifact registry for each required item.", kind: "data_fetch", result: "{ missing: ['security_review'] }" },
      { id: "t2", name: "Reviewer notification",  whenLabel: "09:29:19", summary: "Notified the project lead + security reviewer.",      kind: "external_api", result: "{ sent: 2 }" },
    ],
    policyRules: [
      { id: "r1", label: "Security review required for Design → Build", outcome: "fail" },
    ],
    reasoning: [
      "Required artifact 'security_review' is missing.",
      "Per policy, transition is blocked until artifact is attached.",
      "Notified project lead and security reviewer to unblock.",
    ],
    output: { action: "block", missing: ["security_review"], notifiedRoles: ["pm", "secops"] },
  },
};

export const DELIVERY_AGENT_REGISTRY: AgentRegistry = {
  module: "delivery",
  agents: AGENTS,
  decisions: DECISIONS,
  traces: TRACES,
};
