/* ================================================================
   Legal & Legal Ops — Agent Tower registry
   ================================================================ */

import type {
  AgentDecision,
  AgentRegistry,
  AgentSpec,
  DecisionTrace,
} from "@/components/agents/types";

const AGENTS: AgentSpec[] = [
  {
    id: "intake_routing",
    name: "Intake & Routing",
    purpose: "Classifies every legal ask, gathers context, routes to the right counsel or deflects to self-serve.",
    description:
      "First touch for every legal request — from Slack, email, web form, or another module's event bus. Classifies by type (NDA, vendor MSA, employment, IP, litigation, privacy, regulatory), pulls related context (deal, vendor, employee, prior matters), picks an SLA, and either opens a matter or hands the user a self-serve answer. The judgment queue stays focused on the 30% that actually needs a lawyer.",
    trigger: "on_event",
    triggerDetail: "Every new legal ask (any channel)",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_requests"] },
    tone: "brand",
    iconName: "Captions",
    activity7d: [38, 41, 29, 47, 52, 9, 16],
    accuracy30d: 0.92,
    overrideRate30d: 0.08,
    kpis: [
      { label: "Self-serve deflection",         value: "64%",     hint: "Requests resolved without a lawyer", trend: "up" },
      { label: "Avg routing time",               value: "3.2 min", hint: "From submission to assigned",        trend: "up" },
    ],
    recentActions: [
      { id: "ra-ir-1", when: "4m ago",  text: "Routed Sumitomo NDA to commercial team (M Ravi); SLA 24h." },
      { id: "ra-ir-2", when: "21m ago", text: "Deflected 'do I need an NDA for a podcast' → playbook §1.2 + 2 templates." },
      { id: "ra-ir-3", when: "1h ago",  text: "Escalated to GC: regulator inquiry from Bank of England." },
    ],
    requiredPermissions: ["legal.matter.read", "legal.matter.write"],
  },
  {
    id: "nda_triage",
    name: "NDA Triage",
    purpose: "GREEN / YELLOW / RED on every NDA; generates redlines automatically when non-standard.",
    description:
      "The single most repetitive Legal task. Compares incoming counterparty NDA against our standard form, scores it GREEN (sign as-is), YELLOW (light review needed), or RED (full review). When YELLOW or RED, drafts a redline against our playbook positions with rationale per clause.",
    trigger: "on_event",
    triggerDetail: "On NDA arriving via intake or upload",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["mutual_nda", "one_way_nda"] },
    tone: "success",
    iconName: "ShieldCheck",
    activity7d: [22, 18, 27, 31, 24, 3, 7],
    accuracy30d: 0.94,
    overrideRate30d: 0.06,
    kpis: [
      { label: "NDA cycle time",      value: "1.4 days", hint: "Median across last 60 days", trend: "up" },
      { label: "GREEN auto-routed",   value: "71%",      hint: "Of NDAs auto-cleared",       trend: "up" },
    ],
    recentActions: [
      { id: "ra-nt-1", when: "2m ago",   text: "Sumitomo NDA → YELLOW; flagged §7 (indemnity carve-out)." },
      { id: "ra-nt-2", when: "55m ago",  text: "Lumen Health NDA → GREEN; auto-routed to e-signature." },
      { id: "ra-nt-3", when: "Yesterday", text: "BBL NDA → RED; counterparty's MSA-style clauses inside NDA wrapper." },
    ],
    requiredPermissions: ["legal.contract.read", "legal.contract.draft"],
  },
  {
    id: "contract_review",
    name: "Contract Review",
    purpose: "Reviews counterparty paper clause-by-clause against the playbook; suggests redlines with rationale.",
    description:
      "Scales legal review across MSAs, SOWs, DPAs, vendor agreements, customer agreements. Walks each clause, compares to playbook positions (must-have / nice-to-have / fallback), flags deviations, drafts redline language, and annotates with playbook citations. Lawyer reviews the agent's notes, doesn't read the contract cold.",
    trigger: "on_event",
    triggerDetail: "On new draft or counterparty paper uploaded",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["msa", "sow", "dpa", "vendor", "customer"] },
    tone: "brand-purple",
    iconName: "FileText",
    activity7d: [8, 11, 9, 13, 12, 2, 4],
    accuracy30d: 0.88,
    overrideRate30d: 0.12,
    kpis: [
      { label: "Lawyer review time",       value: "−47%", hint: "Pre-marked draft vs cold read",    trend: "up" },
      { label: "Deviation catch rate",     value: "96%",  hint: "Clauses flagged vs final markup",  trend: "up" },
    ],
    recentActions: [
      { id: "ra-cr-1", when: "12m ago",   text: "Acme MSA: 14 deviations from playbook; auto-drafted redline." },
      { id: "ra-cr-2", when: "1h ago",    text: "PMI Japan SOW: clean — only payment-terms variance (acceptable)." },
      { id: "ra-cr-3", when: "Yesterday", text: "Snowflake DPA: 3 P0 issues — flagged for partner review." },
    ],
    requiredPermissions: ["legal.contract.read", "legal.contract.draft", "legal.playbook.read"],
  },
  {
    id: "negotiation_copilot",
    name: "Negotiation Co-Pilot",
    purpose: "Drafts counter-positions from the playbook and analogous past deals.",
    description:
      "Sits with the lawyer mid-negotiation. When the counterparty rejects a clause or proposes alternatives, the agent surfaces (a) playbook fallback positions, (b) language we accepted on analogous past deals (with deal value, counterparty type, outcome), (c) draft response language. Enforces concession discipline — flags when we're giving up more than we typically do for this counterparty size.",
    trigger: "on_event",
    triggerDetail: "During active redline cycles",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["active_negotiations"] },
    tone: "brand-purple",
    iconName: "MessagesSquare",
    activity7d: [14, 17, 11, 19, 22, 4, 9],
    accuracy30d: 0.85,
    overrideRate30d: 0.15,
    kpis: [
      { label: "Cycle time / redline round", value: "−32%",     hint: "Avg across last 40 deals",     trend: "up" },
      { label: "Concession discipline",       value: "+18 pp",  hint: "Held positions vs benchmark", trend: "up" },
    ],
    recentActions: [
      { id: "ra-nc-1", when: "8m ago",   text: "Acme: surfaced 3 analogous deals where we held LoL at 12 mo fees." },
      { id: "ra-nc-2", when: "47m ago",  text: "BBL: drafted counter on AR-trigger language; cited playbook §4.3." },
      { id: "ra-nc-3", when: "Yesterday", text: "Flagged concession-drift on Lumen IP indemnity (lower than benchmark)." },
    ],
  },
  {
    id: "obligation_extractor",
    name: "Obligation Extractor",
    purpose: "Parses signed contracts, extracts obligations + dates + owners; creates tracker entries.",
    description:
      "Closes the loop after signature. Reads the executed contract, extracts every obligation we owe and every obligation the counterparty owes — SLAs, audit rights, notice periods, data-handling commitments, indemnities, renewal windows, exclusivity, MFNs. Assigns an owner (e.g. SRE for uptime, Finance for invoicing) and creates tracker entries with due dates.",
    trigger: "on_event",
    triggerDetail: "On contract execution / countersignature",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["signed_contracts"] },
    tone: "brand-teal",
    iconName: "ListChecks",
    activity7d: [3, 5, 4, 6, 8, 1, 2],
    accuracy30d: 0.91,
    overrideRate30d: 0.09,
    kpis: [
      { label: "Contracts with structured obligations", value: "98%",  hint: "Of contracts signed in last 90d", trend: "up" },
      { label: "Obligation breaches caught early",       value: "+4×",  hint: "Vs pre-agent baseline",          trend: "up" },
    ],
    recentActions: [
      { id: "ra-oe-1", when: "1h ago",     text: "Acme MSA: 23 obligations extracted; SRE/Finance/Legal owners assigned." },
      { id: "ra-oe-2", when: "Yesterday",  text: "Snowflake DPA: 11 data-handling obligations + 4 audit rights." },
      { id: "ra-oe-3", when: "3d ago",     text: "Sumitomo NDA: 5 confidentiality obligations + return-of-info clock (3y)." },
    ],
    requiredPermissions: ["legal.contract.read", "legal.obligation.write"],
  },
  {
    id: "renewal_sentinel",
    name: "Renewal Sentinel",
    purpose: "Surfaces upcoming renewals at 120/60/30 days with usage data and recommendation.",
    description:
      "Stops auto-renew leakage. Scans every active contract daily. At 120 days surfaces the renewal for budget consideration. At 60 days requires a decision (renew / renegotiate / terminate). At 30 days escalates if no decision. Brings the data: usage, support tickets, business owner sentiment, market alternatives.",
    trigger: "scheduled",
    triggerDetail: "Daily 06:00 UTC",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["active_contracts"] },
    tone: "warning",
    iconName: "Bell",
    activity7d: [2, 3, 1, 4, 5, 0, 1],
    accuracy30d: 0.97,
    overrideRate30d: 0.03,
    kpis: [
      { label: "Renewals decided on time",     value: "94%",   hint: "Up from 61% baseline",        trend: "up" },
      { label: "Auto-renew leakage prevented", value: "₹84L",  hint: "Last 12 months",              trend: "up" },
    ],
    recentActions: [
      { id: "ra-rs-1", when: "Today",        text: "Snowflake @ 120d: usage flat, 2 alternatives priced; recommend renegotiate −12%." },
      { id: "ra-rs-2", when: "Yesterday",    text: "DocuSign @ 60d: usage +18%, no alternatives strong; recommend renew." },
      { id: "ra-rs-3", when: "2d ago",       text: "ABC Vendor @ 30d ESCALATED: no decision logged; GC notified." },
    ],
  },
  {
    id: "compliance_watchdog_legal",
    name: "Compliance Watchdog",
    purpose: "Monitors regulator + statute feeds; flags impacted policies and contracts; drafts redlines.",
    description:
      "Watches official-gazette + regulator feeds across IN/UK/US/EU/JP/SG. When a rule changes, identifies which contracts and policies touch the affected area (data, employment, AML, sanctions, AI, sector-specific), drafts the redline, and notifies the matter owner. Builds the audit trail showing we noticed and responded within the regulator's window.",
    trigger: "continuous",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["IN", "UK", "US", "EU", "JP", "SG"] },
    tone: "warning",
    iconName: "TriangleAlert",
    activity7d: [4, 2, 6, 3, 5, 1, 2],
    accuracy30d: 0.96,
    overrideRate30d: 0.04,
    kpis: [
      { label: "Time-to-compliance after rule change", value: "−68%", hint: "Median days to redline complete", trend: "up" },
      { label: "Rule changes triaged",                  value: "47",  hint: "Last 30 days",                    trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-cw-1", when: "2h ago",    text: "EU AI Act Annex III update: 3 customer contracts + 1 policy affected; redlines drafted." },
      { id: "ra-cw-2", when: "Yesterday", text: "India DPDP rules notification: privacy policy v4 drafted for review." },
      { id: "ra-cw-3", when: "3d ago",    text: "UK PSR safeguarding rule: 5 vendor DPAs need supplementary terms." },
    ],
    requiredPermissions: ["legal.compliance.read", "legal.compliance.act"],
  },
  {
    id: "dsar_handler",
    name: "Privacy / DSAR Handler",
    purpose: "End-to-end DSAR workflow — verify identity, fan-out to data owners, compile redacted response.",
    description:
      "Owns the DSAR lifecycle. Verifies the subject's identity, fans the request out to every data owner across HR, CRM, Talent, Delivery, IT, Finance, Knowledge, posts SLA reminders, gathers responses, applies redactions for third-party data, compiles the response package, and ships to the subject within the jurisdictional window (DPDP 30d / GDPR 30d / CCPA 45d). Shares lifecycle with the HR DSAR queue.",
    trigger: "on_event",
    triggerDetail: "On DSAR submission",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["dsar"] },
    tone: "destructive",
    iconName: "ShieldCheck",
    activity7d: [1, 2, 1, 0, 3, 0, 1],
    accuracy30d: 0.93,
    overrideRate30d: 0.07,
    kpis: [
      { label: "SLA hit rate",         value: "100%",  hint: "DSARs delivered within window",   trend: "up" },
      { label: "Lawyer hours per DSAR", value: "1.8h", hint: "Down from 9h pre-agent",          trend: "up" },
    ],
    recentActions: [
      { id: "ra-ds-1", when: "Today",     text: "DSAR-2026-12 (access): 8/8 data owners responded; redacted package ready for review." },
      { id: "ra-ds-2", when: "Yesterday", text: "DSAR-2026-11 (deletion): legal-hold conflict flagged on 1 record; escalated." },
      { id: "ra-ds-3", when: "3d ago",    text: "DSAR-2026-10 (portability): JSON + CSV package shipped to subject." },
    ],
    requiredPermissions: ["legal.dsar.read", "legal.dsar.act"],
  },
  {
    id: "dpia_copilot",
    name: "DPIA Co-Pilot",
    purpose: "Drafts Data Protection Impact Assessments from system description + data inventory.",
    description:
      "When a new product, feature, or system is registered, identifies whether a DPIA is required (GDPR Art. 35 / DPDP §10), drafts the assessment from the system description, data inventory, and processing purposes. Pre-fills risk register and mitigation suggestions. Lawyer reviews instead of starting from a blank doc.",
    trigger: "on_event",
    triggerDetail: "On new product/system registration",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["new_systems"] },
    tone: "brand-purple",
    iconName: "Library",
    activity7d: [1, 0, 1, 2, 1, 0, 0],
    accuracy30d: 0.87,
    overrideRate30d: 0.13,
    kpis: [
      { label: "DPIAs completed before launch", value: "92%", hint: "Of high-risk systems",        trend: "up" },
      { label: "DPIA draft → final cycle time", value: "5d",  hint: "Down from 18d pre-agent",     trend: "up" },
    ],
    recentActions: [
      { id: "ra-dp-1", when: "Yesterday", text: "DPIA drafted for new 'Talent skills-graph' feature (biometric inferences? no)." },
      { id: "ra-dp-2", when: "1w ago",    text: "DPIA for vendor 'CallTrack' rejected — vendor's controls insufficient." },
      { id: "ra-dp-3", when: "2w ago",    text: "DPIA for 'AI Standup Synthesiser' completed; transparency notice issued." },
    ],
  },
  {
    id: "spend_auditor",
    name: "Spend Auditor",
    purpose: "Reviews outside-counsel invoices line-by-line vs OCG and rate cards; flags exceptions.",
    description:
      "When an outside counsel invoice arrives, walks every line against the Outside Counsel Guidelines: rate vs agreed rate card, block billing, vague descriptors, partner doing associate work, duplicate entries, travel & administrative violations. Flags exceptions and routes for partner approval. Tracks recoveries.",
    trigger: "on_event",
    triggerDetail: "On outside-counsel invoice upload",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["external_counsel_invoices"] },
    tone: "success",
    iconName: "Gauge",
    activity7d: [3, 5, 2, 7, 4, 0, 1],
    accuracy30d: 0.95,
    overrideRate30d: 0.05,
    kpis: [
      { label: "Invoice review time",     value: "−81%",  hint: "Vs manual line-by-line",   trend: "up" },
      { label: "Recoveries (FY-to-date)", value: "₹62L", hint: "Across 8 panel firms",     trend: "up" },
    ],
    recentActions: [
      { id: "ra-sa-1", when: "30m ago",   text: "Kotak Legal invoice: 12 line violations; ₹3.8L flagged for write-down." },
      { id: "ra-sa-2", when: "Yesterday", text: "BlackRidge invoice: clean; auto-approved at partner threshold." },
      { id: "ra-sa-3", when: "2d ago",    text: "Cyril Amarchand: partner-doing-associate-work flag; ₹1.2L disputed." },
    ],
    requiredPermissions: ["legal.spend.read", "legal.spend.act"],
  },
  {
    id: "matter_summariser",
    name: "Matter Summariser",
    purpose: "Drafts matter status for GC / board; cross-matter summaries by category.",
    description:
      "Replaces the GC's Sunday-evening spreadsheet exercise. Reads every active matter, drafts a status: posture, last 7-day events, blocking risks, asks. Rolls up by category (commercial, employment, IP, litigation, regulatory) for board reporting. Aware of audience: board view hides privileged content unless reviewer toggles it.",
    trigger: "scheduled",
    triggerDetail: "Weekly + on demand",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["active_matters"] },
    tone: "brand",
    iconName: "FileText",
    activity7d: [1, 1, 1, 1, 1, 0, 0],
    accuracy30d: 0.91,
    overrideRate30d: 0.09,
    kpis: [
      { label: "GC prep time per board",     value: "−74%", hint: "Vs manual rollup",         trend: "up" },
      { label: "Board readout accuracy",     value: "98%",  hint: "Vs lawyer-corrected gold", trend: "up" },
    ],
    recentActions: [
      { id: "ra-ms-1", when: "Today",      text: "Drafted weekly GC summary across 47 active matters; 3 critical flagged." },
      { id: "ra-ms-2", when: "Last Mon",   text: "Board pack: litigation rollup, regulator update, top-5 risk items." },
      { id: "ra-ms-3", when: "2w ago",     text: "Cross-matter pattern: 4 customer indemnity disputes; root-cause flagged." },
    ],
  },
  {
    id: "policy_qa",
    name: "Policy & Knowledge Q&A",
    purpose: "Answers legal questions from playbook, policy, precedent — with citations.",
    description:
      "The self-serve front door. 'Can I share this with a candidate before they sign an NDA?' 'What's our position on most-favoured-nation clauses?' 'Who's the data controller in this scenario?' Answers grounded in playbook + policy library + precedent matters, with citations. Hands off to a lawyer when confidence is low or the answer would be commercially material.",
    trigger: "on_event",
    triggerDetail: "On user question (any channel)",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_employees"] },
    tone: "brand-teal",
    iconName: "MessageCircle",
    activity7d: [22, 28, 19, 34, 31, 4, 11],
    accuracy30d: 0.89,
    overrideRate30d: 0.11,
    kpis: [
      { label: "Self-serve resolution",    value: "68%",   hint: "Without lawyer touch",     trend: "up" },
      { label: "Citation accuracy",        value: "97%",   hint: "Citations resolve correctly", trend: "up" },
    ],
    recentActions: [
      { id: "ra-pq-1", when: "5m ago",    text: "'Can sales send our standard MSA to a JP customer in JPY?' — answered with playbook §3.1 + 2 prior deals." },
      { id: "ra-pq-2", when: "32m ago",   text: "'Is this clause MFN?' — yes; cited customer playbook + handed to lawyer." },
      { id: "ra-pq-3", when: "1h ago",    text: "'What's our IP-assignment language for contractors?' — template returned." },
    ],
  },
  {
    id: "conflict_checker",
    name: "Conflict Checker",
    purpose: "Cross-references parties for COI on every new matter or counsel engagement.",
    description:
      "Before a matter opens or external counsel is engaged, runs the conflict check: counterparty, affiliates, beneficial owners, related directors, prior representations. Flags potential conflicts of interest and ethical walls. Maintains the COI register.",
    trigger: "on_event",
    triggerDetail: "On matter creation + counsel engagement",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["new_matters", "counsel_engagements"] },
    tone: "destructive",
    iconName: "ShieldCheck",
    activity7d: [2, 3, 1, 2, 4, 0, 1],
    accuracy30d: 0.99,
    overrideRate30d: 0.01,
    kpis: [
      { label: "COI incidents avoided",    value: "12",     hint: "Last 12 months",             trend: "up" },
      { label: "Auto-cleared engagements", value: "82%",    hint: "Of new engagements",         trend: "up" },
    ],
    recentActions: [
      { id: "ra-cc-1", when: "1h ago",    text: "Sumitomo matter: COI clear (no prior reps in chain)." },
      { id: "ra-cc-2", when: "Yesterday", text: "Engaging Kotak on BBL — flagged: Kotak partner sits on Lumen board." },
      { id: "ra-cc-3", when: "3d ago",    text: "Ethical wall requested for 2 internal lawyers (M&A vs litigation matter)." },
    ],
  },
  {
    id: "litigation_hold",
    name: "Litigation Hold",
    purpose: "Identifies custodians, sends notices, tracks attestations, coordinates departures.",
    description:
      "When a litigation hold is issued, the agent identifies all custodians (by role + matter relevance), sends preservation notices, tracks attestations, and crucially coordinates with HR for any custodian leaving the company — so we don't lose data when someone offboards mid-hold. Reduces hold-non-compliance risk.",
    trigger: "on_event",
    triggerDetail: "On hold issuance + custodian departure events",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["active_holds"] },
    tone: "destructive",
    iconName: "ShieldCheck",
    activity7d: [1, 0, 0, 1, 2, 0, 0],
    accuracy30d: 0.98,
    overrideRate30d: 0.02,
    kpis: [
      { label: "Hold compliance",        value: "100%",  hint: "Past 12 months",                  trend: "up" },
      { label: "Departure conflicts caught", value: "4", hint: "Custodians flagged on offboard", trend: "up" },
    ],
    recentActions: [
      { id: "ra-lh-1", when: "Yesterday", text: "Acme dispute hold expanded: +6 custodians (Sales + RevOps); notices sent." },
      { id: "ra-lh-2", when: "1w ago",    text: "Caught: Anil Sharma offboard mid-hold on regulator matter; data preserved." },
      { id: "ra-lh-3", when: "3w ago",    text: "BBL inquiry hold issued; 14 custodians attested within 48h (SLA)." },
    ],
  },
  {
    id: "ma_diligence",
    name: "M&A Diligence",
    purpose: "Builds diligence checklist from playbook + deal type; chases responses; flags gaps.",
    description:
      "Drops the cycle time on M&A diligence by an order of magnitude. Pulls the right diligence checklist for deal type (asset / share / merger), chases responses across the target's data room and ours, flags missing or stale documents, surfaces red flags by category, drafts the diligence report. Coordinates with Finance + HR + IT diligence streams.",
    trigger: "on_event",
    triggerDetail: "On M&A matter opening",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["ma_matters"] },
    tone: "brand-purple",
    iconName: "Library",
    activity7d: [0, 0, 0, 1, 1, 0, 0],
    accuracy30d: 0.90,
    overrideRate30d: 0.10,
    kpis: [
      { label: "Diligence cycle time",   value: "−54%",  hint: "Vs prior 3 deals avg",         trend: "up" },
      { label: "Material findings caught early", value: "100%", hint: "Of items flagged post-close", trend: "up" },
    ],
    recentActions: [
      { id: "ra-md-1", when: "Yesterday", text: "Target X (asset deal): drafted 187-item diligence list; 14 P0s flagged." },
      { id: "ra-md-2", when: "1w ago",    text: "Target X: chased 23 outstanding items; 8 received, 4 escalated to GC." },
      { id: "ra-md-3", when: "3w ago",    text: "Target X red-flag report: open litigation + 2 expiring patents." },
    ],
  },
  {
    id: "board_secretary",
    name: "Board / Corporate Secretary",
    purpose: "Drafts agenda, papers, resolutions, minutes; tracks signatures.",
    description:
      "Cuts the corporate secretary cycle. Drafts agenda from prior minutes + outstanding actions, drafts papers from underlying source data (financials, audit, commercial), drafts resolutions and minutes, tracks director signatures. Coordinates with Finance for board financials and with HR for committee composition changes.",
    trigger: "scheduled",
    triggerDetail: "On board / committee cycle",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["board", "audit_committee", "remco"] },
    tone: "brand",
    iconName: "FileText",
    activity7d: [0, 1, 0, 0, 1, 0, 0],
    accuracy30d: 0.93,
    overrideRate30d: 0.07,
    kpis: [
      { label: "Board cycle time",        value: "−42%",  hint: "Vs manual prep",                trend: "up" },
      { label: "Resolutions auto-drafted", value: "47",   hint: "Last 12 months",                 trend: "up" },
    ],
    recentActions: [
      { id: "ra-bs-1", when: "Yesterday", text: "Q2 board pack drafted: 11 papers + 4 resolutions; sent for review." },
      { id: "ra-bs-2", when: "1w ago",    text: "Audit committee minutes drafted; 2 action items tracked back to last meeting." },
      { id: "ra-bs-3", when: "3w ago",    text: "RemCo: draft resolutions on FY26 ESOP pool refresh." },
    ],
    requiredPermissions: ["legal.board.read", "legal.board.act"],
  },
  {
    id: "regulatory_reporting",
    name: "Regulatory Reporting",
    purpose: "Drafts statutory filings and regulator reports from system data.",
    description:
      "Owns the calendar of statutory filings — corporate, tax, sectoral, sanctions, beneficial ownership. Draws data from Finance, HR, Cap Table, and product systems to draft each filing, validates against rules, and routes for sign-off. Files on time and keeps the audit trail.",
    trigger: "scheduled",
    triggerDetail: "Per filing calendar (daily check)",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["statutory_filings"] },
    tone: "warning",
    iconName: "ShieldCheck",
    activity7d: [1, 1, 1, 1, 1, 0, 0],
    accuracy30d: 0.99,
    overrideRate30d: 0.01,
    kpis: [
      { label: "On-time filing rate",       value: "100%", hint: "Past 24 months",            trend: "up" },
      { label: "Filings auto-drafted",      value: "31",   hint: "Last 12 months",             trend: "up" },
    ],
    recentActions: [
      { id: "ra-rr-1", when: "Today",     text: "MCA Form MGT-7 (FY26 annual return) — draft 90% complete; pending director attestations." },
      { id: "ra-rr-2", when: "Yesterday", text: "FCA submission (PSR notifications) — drafted; counsel review queued." },
      { id: "ra-rr-3", when: "3d ago",    text: "RBI FLA return — filed on time; receipt logged." },
    ],
  },
  {
    id: "ethics_whistleblower",
    name: "Ethics & Whistleblower",
    purpose: "Triages hotline submissions; anonymises; routes confidentially to investigators.",
    description:
      "The most sensitive surface in the module. Receives every whistleblower / ethics hotline submission, runs initial classification (urgency, category, jurisdictional reporting obligations), anonymises identifying details where allowed, routes to the appropriate investigator with privilege scoping. Tracks SLAs against jurisdictional whistleblower-protection windows. Audit-only access — even other Legal agents cannot see contents.",
    trigger: "on_event",
    triggerDetail: "On hotline submission (any channel)",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["hotline_submissions"] },
    tone: "destructive",
    iconName: "Lightbulb",
    activity7d: [0, 1, 0, 0, 1, 0, 0],
    accuracy30d: 0.94,
    overrideRate30d: 0.06,
    kpis: [
      { label: "Time to first triage",        value: "1.1h", hint: "From submission",          trend: "up" },
      { label: "Reporting-window compliance",  value: "100%", hint: "Jurisdictional windows",   trend: "up" },
    ],
    recentActions: [
      { id: "ra-ew-1", when: "Yesterday", text: "Hotline ETH-2026-04 (financial controls): routed confidentially to audit chair." },
      { id: "ra-ew-2", when: "1w ago",    text: "Hotline ETH-2026-03 (workplace): routed to People Ops + outside counsel co-investigation." },
      { id: "ra-ew-3", when: "3w ago",    text: "Hotline ETH-2026-02 (data misuse): privacy review triggered; matter opened." },
    ],
    requiredPermissions: ["legal.ethics.read", "legal.ethics.act"],
  },
];

const DECISIONS: AgentDecision[] = [
  { id: "ld-1",  agentId: "intake_routing",         whenISO: "2026-05-12T11:30:00", whenLabel: "4m ago",   summary: "Routed Sumitomo NDA to commercial team (M Ravi); SLA 24h.",                    outcome: "executed",      confidence: 92, recordId: "m-sumi-nda",  recordLabel: "Sumitomo NDA · M-2026-0418" },
  { id: "ld-2",  agentId: "nda_triage",             whenISO: "2026-05-12T11:32:00", whenLabel: "2m ago",   summary: "Sumitomo NDA → YELLOW. Indemnity carve-out (§7) outside playbook range.",        outcome: "suggested",     confidence: 86, recordId: "m-sumi-nda",  recordLabel: "Sumitomo NDA · M-2026-0418" },
  { id: "ld-3",  agentId: "contract_review",        whenISO: "2026-05-12T11:22:00", whenLabel: "12m ago",  summary: "Acme MSA review: 14 deviations from playbook; redline drafted (28 inline edits).", outcome: "suggested",   confidence: 91, recordId: "m-acme-msa",  recordLabel: "Acme MSA Phase 2 · M-2026-0410" },
  { id: "ld-4",  agentId: "renewal_sentinel",       whenISO: "2026-05-12T06:00:00", whenLabel: "Today",    summary: "Snowflake renewal in 120 days. Usage flat; alternatives priced. Recommend renegotiate −12%.", outcome: "suggested", confidence: 94, recordId: "v-snowflake", recordLabel: "Snowflake (vendor)" },
  { id: "ld-5",  agentId: "compliance_watchdog_legal", whenISO: "2026-05-12T09:30:00", whenLabel: "2h ago", summary: "EU AI Act Annex III update: 3 customer contracts + 1 policy affected; redlines drafted.", outcome: "suggested", confidence: 97, recordId: "rule-eu-ai-act", recordLabel: "EU AI Act Annex III amendment" },
  { id: "ld-6",  agentId: "dsar_handler",           whenISO: "2026-05-12T08:00:00", whenLabel: "Today",    summary: "DSAR-2026-12 (access): 8/8 data owners responded; redacted package ready for review.", outcome: "pending_review", confidence: 95, recordId: "dsar-2026-12", recordLabel: "DSAR-2026-12" },
  { id: "ld-7",  agentId: "spend_auditor",          whenISO: "2026-05-12T11:00:00", whenLabel: "30m ago",  summary: "Kotak Legal invoice: 12 line violations; ₹3.8L flagged for write-down.",         outcome: "suggested",     confidence: 96, recordId: "inv-kotak-042",  recordLabel: "Kotak Legal · INV-042" },
  { id: "ld-8",  agentId: "obligation_extractor",   whenISO: "2026-05-12T10:30:00", whenLabel: "1h ago",   summary: "Acme MSA: 23 obligations extracted; SRE/Finance/Legal owners assigned.",         outcome: "executed",      confidence: 93, recordId: "m-acme-msa",      recordLabel: "Acme MSA Phase 2" },
  { id: "ld-9",  agentId: "matter_summariser",      whenISO: "2026-05-12T07:00:00", whenLabel: "Today",    summary: "Weekly GC summary drafted across 47 active matters; 3 critical flagged for board.", outcome: "pending_review", confidence: 90, recordId: "summary-2026-w19", recordLabel: "GC weekly · W19" },
  { id: "ld-10", agentId: "policy_qa",              whenISO: "2026-05-12T11:35:00", whenLabel: "5m ago",   summary: "Q: 'Can sales send our standard MSA to a JP customer in JPY?' — answered with playbook §3.1 + 2 prior deals.", outcome: "executed", confidence: 89 },
  { id: "ld-11", agentId: "conflict_checker",       whenISO: "2026-05-12T10:00:00", whenLabel: "1h ago",   summary: "Engaging Kotak on BBL — flagged: Kotak partner sits on Lumen board. Ethical wall recommended.", outcome: "suggested", confidence: 99, recordId: "engage-kotak-bbl", recordLabel: "Kotak engagement · BBL" },
  { id: "ld-12", agentId: "negotiation_copilot",    whenISO: "2026-05-12T11:24:00", whenLabel: "8m ago",   summary: "Acme: surfaced 3 analogous deals where we held LoL cap at 12 months fees; drafted counter.", outcome: "suggested", confidence: 87, recordId: "m-acme-msa", recordLabel: "Acme MSA Phase 2" },
  { id: "ld-13", agentId: "dpia_copilot",           whenISO: "2026-05-11T16:00:00", whenLabel: "Yesterday", summary: "DPIA drafted for 'Talent skills-graph' feature; no biometrics; medium risk; mitigations suggested.", outcome: "suggested", confidence: 85, recordId: "dpia-skills-graph", recordLabel: "DPIA · Skills graph" },
  { id: "ld-14", agentId: "litigation_hold",        whenISO: "2026-05-11T15:30:00", whenLabel: "Yesterday", summary: "Acme dispute hold expanded: +6 custodians (Sales + RevOps); notices sent.", outcome: "executed", confidence: 98, recordId: "hold-acme-001", recordLabel: "Acme dispute · Hold #1" },
  { id: "ld-15", agentId: "ma_diligence",           whenISO: "2026-05-11T14:00:00", whenLabel: "Yesterday", summary: "Target X (asset deal): drafted 187-item diligence list; 14 P0 items flagged.", outcome: "suggested", confidence: 88, recordId: "ma-target-x", recordLabel: "M&A · Target X" },
  { id: "ld-16", agentId: "board_secretary",        whenISO: "2026-05-11T11:00:00", whenLabel: "Yesterday", summary: "Q2 board pack drafted: 11 papers + 4 resolutions; sent for chair review.", outcome: "pending_review", confidence: 92, recordId: "board-q2-2026", recordLabel: "Q2 2026 board" },
  { id: "ld-17", agentId: "regulatory_reporting",   whenISO: "2026-05-12T08:30:00", whenLabel: "Today",    summary: "MCA Form MGT-7 (FY26 annual return) — draft 90% complete; pending director attestations.", outcome: "pending_review", confidence: 96, recordId: "filing-mca-mgt7-fy26", recordLabel: "MCA MGT-7 · FY26" },
  { id: "ld-18", agentId: "ethics_whistleblower",   whenISO: "2026-05-11T13:00:00", whenLabel: "Yesterday", summary: "Hotline ETH-2026-04 (financial controls): triaged + routed confidentially to audit chair.", outcome: "executed", confidence: 94, recordId: "hotline-eth-2026-04", recordLabel: "Hotline · ETH-2026-04" },
];

const TRACES: Record<string, DecisionTrace> = {
  "ld-2": {
    decisionId: "ld-2",
    input: [
      { label: "Counterparty",     value: "Sumitomo Trading Co." },
      { label: "Document",         value: "Mutual NDA · 6 pages · uploaded 11:30" },
      { label: "Playbook version", value: "NDA Playbook v3.4 (effective 2026-04-01)" },
    ],
    tools: [
      { id: "t1", name: "Clause extraction",      whenLabel: "11:31:08", summary: "Parsed and segmented 18 clauses.",                            kind: "model_call",   result: "{ clauses: 18, pages: 6 }" },
      { id: "t2", name: "Playbook clause match",  whenLabel: "11:31:21", summary: "Matched each clause against playbook positions.",            kind: "data_fetch",   result: "{ matched: 17, novel: 1 }" },
      { id: "t3", name: "Deviation scoring",      whenLabel: "11:31:34", summary: "Scored each matched clause against acceptable range.",       kind: "calc",         result: "{ green: 14, yellow: 3, red: 0 }" },
      { id: "t4", name: "Indemnity carve-out check", whenLabel: "11:31:42", summary: "§7 carve-out flagged: removes our IP-related indemnity.", kind: "policy_lookup", result: "{ section: '§7', position: 'must_have', counterparty_text: 'EXCLUDED' }" },
      { id: "t5", name: "Redline draft (yellow)", whenLabel: "11:31:58", summary: "Drafted 3 redlines with rationale, ready for lawyer review.", kind: "model_call",   result: "{ redlines: 3, total_inline_edits: 7 }" },
    ],
    policyRules: [
      { id: "r1", label: "§7 indemnity carve-outs require playbook fallback or escalation", outcome: "warn" },
      { id: "r2", label: "Term ≤ 3 years for mutual NDAs", outcome: "pass" },
      { id: "r3", label: "Choice of law within accepted set (Delaware / Singapore / India)", outcome: "pass" },
    ],
    reasoning: [
      "17 of 18 clauses match playbook within accepted ranges.",
      "Indemnity carve-out (§7) removes our IP-related coverage — outside acceptable range.",
      "Per playbook escalation rule, this is YELLOW (light review), not RED (full review).",
      "Auto-drafted redline reinstates IP indemnity with mutual carve-out for pre-existing IP.",
    ],
    output: {
      score: "YELLOW",
      reviewerHint: "Indemnity §7 only — 3 redlines pre-drafted.",
      cycleEstimateHours: 4,
      redlineDraftId: "redline-sumi-nda-v1",
    },
  },
  "ld-7": {
    decisionId: "ld-7",
    input: [
      { label: "Firm",         value: "Kotak Legal Counsel" },
      { label: "Invoice",      value: "INV-042 · ₹14,00,000 · 87 line items" },
      { label: "OCG version",  value: "OCG v2.1 (effective 2026-01-01)" },
      { label: "Rate card",    value: "Kotak rate card · effective 2026-04-01" },
    ],
    tools: [
      { id: "t1", name: "Line parse",          whenLabel: "11:00:14", summary: "Parsed 87 line items + metadata.",                                    kind: "data_fetch", result: "{ lines: 87, partner_hours: 21, associate_hours: 64 }" },
      { id: "t2", name: "Rate card match",     whenLabel: "11:00:22", summary: "Matched billed rate vs agreed rate per timekeeper.",                  kind: "data_fetch", result: "{ matches: 80, mismatches: 7 }" },
      { id: "t3", name: "OCG rule check",      whenLabel: "11:00:31", summary: "Walked each line vs OCG rules (block billing, vague descriptors, partner-doing-associate-work, travel & admin).", kind: "policy_lookup", result: "{ violations: 12 }" },
      { id: "t4", name: "Recovery calc",       whenLabel: "11:00:39", summary: "Computed proposed write-down per violation.",                          kind: "calc",       result: "{ write_down: 380000, currency: 'INR' }" },
    ],
    policyRules: [
      { id: "r1", label: "Partner hours doing associate-level work — 50% write-down", outcome: "fail" },
      { id: "r2", label: "Block billing entries > 1.5h — 25% write-down", outcome: "fail" },
      { id: "r3", label: "Vague descriptor (< 6 words) — request resubmission", outcome: "warn" },
      { id: "r4", label: "Travel & admin time — not billable", outcome: "fail" },
    ],
    reasoning: [
      "Partner billed 4 lines totalling 6.8h on tasks classified as associate-level (document collection, basic redlining).",
      "3 entries are block-billed (3h+ in single line, multiple activities).",
      "5 entries have vague descriptors ('matter management').",
      "Total proposed write-down: ₹3.8L (27% of invoice).",
      "Flagged for partner approval before sending to firm; counter-proposal pre-drafted.",
    ],
    output: {
      writeDownINR: 380_000,
      violations: 12,
      requiresPartnerApproval: true,
      counterDraftId: "counter-kotak-042",
    },
  },
};

export const LEGAL_AGENT_REGISTRY: AgentRegistry = {
  module: "legal",
  agents: AGENTS,
  decisions: DECISIONS,
  traces: TRACES,
};
