"use client";

import { motion } from "framer-motion";

const mockActionItems = [
  { priority: "urgent", title: "Review 3 final-round candidates", subtitle: "VP of Engineering · Due today", action: "Review" },
  { priority: "urgent", title: "Approve offer for Marcus Johnson", subtitle: "Senior Backend · $155K · Exp. Mar 27", action: "Approve" },
  { priority: "warning", title: "Complete interview scorecards (2)", subtitle: "Product Designer · From yesterday", action: "Complete" },
  { priority: "warning", title: "Review AI-generated job description", subtitle: "Staff ML Engineer · Recruiter Agent draft", action: "Review" },
  { priority: "normal", title: "Approve onboarding checklist", subtitle: "Maya Chen · Starting Mar 31", action: "View" },
  { priority: "normal", title: "Review weekly hiring report", subtitle: "Auto-generated by Analytics Agent", action: "View" },
  { priority: "normal", title: "Update team headcount plan", subtitle: "Q2 planning · Due Apr 1", action: "Edit" },
] as const;

type Priority = (typeof mockActionItems)[number]["priority"];

const priorityDotColor: Record<Priority, string> = {
  urgent: "bg-destructive",
  warning: "bg-warning",
  normal: "bg-brand",
};

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.06,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 8 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.3, ease: "easeOut" as const },
  },
};

export function ActionItems() {
  return (
    <div className="bg-card border border-border rounded-xl p-5">
      {/* Header */}
      <div className="flex items-center gap-2.5 mb-4">
        <h3 className="text-sm font-semibold text-foreground">
          Needs Your Attention
        </h3>
        <span className="bg-destructive/10 text-destructive text-xs font-bold px-2 py-0.5 rounded-full">
          7
        </span>
      </div>

      {/* Action Items List */}
      <motion.div
        className="flex flex-col gap-2"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {mockActionItems.map((item, index) => (
          <motion.div
            key={index}
            variants={itemVariants}
            className="bg-card border border-border rounded-lg p-4 hover:bg-secondary/30 hover:-translate-y-[1px] transition-all cursor-pointer flex items-center gap-3"
          >
            {/* Priority dot */}
            <div
              className={`w-3 h-3 rounded-full shrink-0 ${priorityDotColor[item.priority]}`}
            />

            {/* Content */}
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-foreground truncate">
                {item.title}
              </p>
              <p className="text-xs text-muted-foreground truncate">
                {item.subtitle}
              </p>
            </div>

            {/* Action button */}
            <button className="text-xs text-brand hover:bg-brand/10 px-2.5 py-1 rounded-md transition-colors shrink-0">
              {item.action}
            </button>
          </motion.div>
        ))}
      </motion.div>
    </div>
  );
}
