/* ================================================================
   Pre-Sales & Proposal Management — Agent Tower registry
   ----------------------------------------------------------------
   18 agents across the bid lifecycle: from RFP intake through
   win/loss debrief. Each spec mirrors the shape used by the Legal
   and Delivery towers so the reusable Tower components render
   uniformly.
   ================================================================ */

import type {
  AgentDecision,
  AgentRegistry,
  AgentSpec,
  DecisionTrace,
} from "@/components/agents/types";

const AGENTS: AgentSpec[] = [
  {
    id: "rfp_decomposer",
    name: "RFP Decomposer",
    purpose: "Parses every requirement, date, form, and evaluation criterion from an RFP within minutes.",
    description:
      "Tears a new RFP / RFI / RFQ into its structural parts: shall-statements, evaluation criteria, page limits, response forms, due dates, mandatory attachments, conflict-of-interest disclosures, and submission rules. Outputs a compliance matrix skeleton so a human can review-and-route, not type-and-collate.",
    trigger: "on_event",
    triggerDetail: "On RFP file upload or capture-tool ingest",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["rfp", "rfi", "rfq"] },
    tone: "brand",
    iconName: "FileText",
    activity7d: [3, 6, 4, 8, 9, 1, 2],
    accuracy30d: 0.94,
    overrideRate30d: 0.06,
    kpis: [
      { label: "Time to compliance matrix", value: "11 min", hint: "Median, prior 30d (was 6 hours manual)", trend: "up" },
      { label: "Requirements extraction",   value: "98.2%",   hint: "Cross-checked vs human reviewer",        trend: "up" },
    ],
    recentActions: [
      { id: "ra-rfp-1", when: "9m ago",  text: "Decomposed Bank of Baroda RFP — 247 shall-statements, 3 mandatory forms, 11 May submission." },
      { id: "ra-rfp-2", when: "2h ago",  text: "Flagged ambiguity in Aviva RFQ §4.2 (deliverable acceptance) — queued for Question Drafter." },
      { id: "ra-rfp-3", when: "5h ago",  text: "Caught a hidden page-limit (Schedule C exhibit cap of 8 pages) on the Mahindra RFP." },
    ],
    requiredPermissions: ["presales.rfp.read", "presales.rfp.write"],
  },

  {
    id: "bid_no_bid",
    name: "Bid / No-Bid Agent",
    purpose: "Scores pursuit fit and win probability against historic analogues; recommends bid or pass.",
    description:
      "Pulls comparable pursuits from the win/loss library, scores fit on capability, geography, capacity, incumbent advantage, and commercial appetite. Surfaces the strongest 'why we win' and 'why we lose' threads, recommends Bid / Bid-with-conditions / No-Bid with rationale and required executive sign-offs.",
    trigger: "on_event",
    triggerDetail: "On new pursuit opened",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_pursuits"] },
    tone: "brand-purple",
    iconName: "Gauge",
    activity7d: [2, 1, 3, 4, 2, 0, 1],
    accuracy30d: 0.81,
    overrideRate30d: 0.19,
    kpis: [
      { label: "CoP ratio",         value: "1 in 2.4", hint: "Cost of Pursuit avoided through No-Bid", trend: "up" },
      { label: "Pursuits won / bid", value: "31%",      hint: "Up from 22% pre-agent",                  trend: "up" },
    ],
    recentActions: [
      { id: "ra-bnb-1", when: "32m ago", text: "Recommended Bid on Mahindra RFP (fit 78%, win prob 41%) — 3 strong analogues." },
      { id: "ra-bnb-2", when: "Yesterday", text: "Recommended No-Bid on Maersk Ops Platform — no operational depth in shipping; estimated CoP avoided ₹38L." },
      { id: "ra-bnb-3", when: "2d ago",   text: "Bid-with-conditions on Aviva — flagged need for UK staffing partner before commit." },
    ],
    requiredPermissions: ["presales.pursuit.read", "presales.pursuit.bid_decide"],
  },

  {
    id: "compliance_matrix_builder",
    name: "Compliance Matrix Builder",
    purpose: "Generates the requirements matrix, tags ownership, tracks coverage to gate review.",
    description:
      "Takes the decomposer output and turns each shall-statement into a row: owner, target section, response status, evidence link, page budget. Tracks coverage live during drafting; flags any requirement that drifts to red and surfaces it on the pursuit dashboard.",
    trigger: "on_event",
    triggerDetail: "On Decomposer output",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_pursuits"] },
    tone: "brand-teal",
    iconName: "ShieldCheck",
    activity7d: [12, 14, 11, 17, 18, 2, 4],
    accuracy30d: 0.96,
    overrideRate30d: 0.04,
    kpis: [
      { label: "Coverage at gate review",  value: "99.1%", hint: "Reqs covered before gold review",         trend: "up" },
      { label: "Owner-tagging accuracy",    value: "92%",  hint: "First-pass assignment correct",           trend: "up" },
    ],
    recentActions: [
      { id: "ra-cmb-1", when: "12m ago", text: "Built matrix for Bank of Baroda (247 reqs) — auto-tagged 219, queued 28 for SME review." },
      { id: "ra-cmb-2", when: "1h ago",  text: "Promoted req §6.3.4 to red — no draft text after 4 days; nudged Sandeep Mehta." },
    ],
    requiredPermissions: ["presales.rfp.read", "presales.rfp.write"],
  },

  {
    id: "capture_copilot",
    name: "Capture Plan Co-Pilot",
    purpose: "Drafts the capture plan from customer intel, competitor data, and historic analogues.",
    description:
      "Composes the first draft of the capture plan: customer profile, decision unit, hot buttons, competitive picture, win themes, ghosting strategy, action register. The capture team's job becomes review-and-edit instead of blank-page authoring.",
    trigger: "on_event",
    triggerDetail: "On capture stage opened",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["capture_stage"] },
    tone: "brand-purple",
    iconName: "Lightbulb",
    activity7d: [1, 2, 1, 3, 4, 0, 1],
    accuracy30d: 0.78,
    overrideRate30d: 0.22,
    kpis: [
      { label: "Plan completeness at kickoff", value: "84%",  hint: "Sections filled before first capture review", trend: "up" },
      { label: "Capture review cycle time",      value: "−42%", hint: "Vs prior baseline (5 days → 2.9)",          trend: "up" },
    ],
    recentActions: [
      { id: "ra-cap-1", when: "1h ago",  text: "Drafted Mahindra capture plan v1 — 7 win themes, 4 ghosting moves identified." },
      { id: "ra-cap-2", when: "Yesterday", text: "Updated Aviva plan after CFO change announcement → adjusted commercial framing." },
    ],
    requiredPermissions: ["presales.capture.read", "presales.capture.write"],
  },

  {
    id: "customer_intel",
    name: "Customer Intel Agent",
    purpose: "Aggregates news, financials, leadership shifts, prior engagement into a live brief.",
    description:
      "Watches every open pursuit's customer 24×7: earnings, analyst notes, leadership moves, public RFP cadence, prior engagement notes from the CRM and Delivery modules. Pushes a daily brief to the pursuit channel; nudges capture lead when something material happens.",
    trigger: "continuous",
    triggerDetail: "Continuous polling + Slack/email push",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_active_pursuits"] },
    tone: "brand-teal",
    iconName: "Activity",
    activity7d: [22, 28, 25, 26, 24, 8, 9],
    accuracy30d: 0.89,
    overrideRate30d: 0.11,
    kpis: [
      { label: "Brief freshness",         value: "<24h", hint: "Median age of customer brief on active pursuits", trend: "up" },
      { label: "Material-event detection", value: "+18%", hint: "Earlier than competitors' open-source signals",  trend: "up" },
    ],
    recentActions: [
      { id: "ra-cust-1", when: "14m ago", text: "Aviva — CFO resigned. Capture lead notified; brief updated." },
      { id: "ra-cust-2", when: "1h ago",  text: "Bank of Baroda Q4 earnings — analytics spend grew 24% YoY; updated win-theme rationale." },
    ],
    requiredPermissions: ["presales.capture.read"],
  },

  {
    id: "competitor_intel",
    name: "Competitor Intel Agent",
    purpose: "Surfaces likely bidders, their positioning, prior win/loss patterns against us.",
    description:
      "Given a pursuit, infers the likely competitor set from public signals (job postings, conference talks, press releases) and our historical experience with that customer. Surfaces each competitor's known positioning, recent press, and our prior win/loss record against them with categorised drivers.",
    trigger: "on_event",
    triggerDetail: "On pursuit opened",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["all_pursuits"] },
    tone: "brand-purple",
    iconName: "TrendingUp",
    activity7d: [2, 3, 1, 3, 4, 0, 1],
    accuracy30d: 0.76,
    overrideRate30d: 0.24,
    kpis: [
      { label: "Anticipated-competitor hit rate", value: "73%",  hint: "Competitors correctly named pre-submission", trend: "up" },
      { label: "Win record vs anticipated set",     value: "+9pp", hint: "When agent's competitor-takedown threads used", trend: "up" },
    ],
    recentActions: [
      { id: "ra-comp-1", when: "1h ago",  text: "Mahindra pursuit — anticipates TCS, Wipro, and a likely incumbent extension (Capgemini)." },
      { id: "ra-comp-2", when: "Yesterday", text: "Bank of Baroda — flagged Accenture aggressive on banking analytics this quarter (4 job postings)." },
    ],
    requiredPermissions: ["presales.capture.read"],
  },

  {
    id: "question_drafter",
    name: "Question Drafter",
    purpose: "Drafts clarifying questions to the customer from ambiguities found in the RFP.",
    description:
      "After Decomposer flags ambiguities, drafts the clarifying questions the bid team should submit during the customer Q&A window. Phrasing optimises for getting a useful answer without telegraphing weakness. Routes for sign-off from capture lead before submission.",
    trigger: "scheduled",
    triggerDetail: "Pre-submission Q&A window opens",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["clarifying_questions"] },
    tone: "brand",
    iconName: "MessageCircle",
    activity7d: [0, 1, 0, 2, 1, 0, 0],
    accuracy30d: 0.83,
    overrideRate30d: 0.17,
    kpis: [
      { label: "Questions submitted",   value: "47",  hint: "Across 6 pursuits prior 30d", trend: "neutral" },
      { label: "Useful-answer rate",     value: "71%", hint: "Customer's answer materially changed our response", trend: "up" },
    ],
    recentActions: [
      { id: "ra-qd-1", when: "3h ago",  text: "Drafted 11 clarifying questions on Mahindra RFP — capture lead approved 9, dropped 2." },
      { id: "ra-qd-2", when: "Yesterday", text: "Aviva — rephrased a question that was leaking our preferred staffing model." },
    ],
    requiredPermissions: ["presales.rfp.write"],
  },

  {
    id: "content_recommender",
    name: "Content Recommender",
    purpose: "Surfaces best-matched prior content from the library for every section being authored.",
    description:
      "Section-aware retrieval. When a SME opens a section, suggests the highest-scoring prior content (with provenance and last-refresh date), highlights where prior text would need updating, and warns when content is stale beyond the refresh threshold.",
    trigger: "continuous",
    triggerDetail: "Section authoring workspace open",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_sections"] },
    tone: "brand-teal",
    iconName: "Library",
    activity7d: [38, 44, 41, 52, 48, 6, 8],
    accuracy30d: 0.88,
    overrideRate30d: 0.12,
    kpis: [
      { label: "Content reuse %",        value: "63%",   hint: "Sections starting from a recommended snippet", trend: "up" },
      { label: "Time to first draft",     value: "−34%",  hint: "Median across last 30d",                       trend: "up" },
    ],
    recentActions: [
      { id: "ra-cr-1", when: "8m ago",  text: "Recommended 3 fraud-detection case studies for Bank of Baroda §3.2." },
      { id: "ra-cr-2", when: "27m ago", text: "Flagged 2 reused passages as stale (>9 months); suggested newer paragraphs." },
    ],
    requiredPermissions: ["presales.library.read", "presales.proposal.read"],
  },

  {
    id: "first_draft_author",
    name: "First-Draft Author",
    purpose: "Seeds a first draft for each assigned section so SMEs refine instead of authoring blank.",
    description:
      "On section assignment, drafts a tailored first version using: the requirement statement, win themes, recommended content, customer-specific terminology, prior proposal voice. SME accepts/edits/replaces; agent never publishes without human sign-off.",
    trigger: "on_event",
    triggerDetail: "On section assigned to SME",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_sections"] },
    tone: "brand",
    iconName: "Captions",
    activity7d: [9, 14, 11, 19, 21, 1, 3],
    accuracy30d: 0.79,
    overrideRate30d: 0.21,
    kpis: [
      { label: "Time saved / section",   value: "2.3 h",  hint: "Vs blank-page baseline",                 trend: "up" },
      { label: "Sections accepted ≥ 70%", value: "61%",    hint: "SME kept at least 70% of seeded text", trend: "up" },
    ],
    recentActions: [
      { id: "ra-fda-1", when: "44m ago", text: "Seeded draft for Bank of Baroda §3.2 (Fraud detection approach) — 1,180 words, 6 citations." },
      { id: "ra-fda-2", when: "2h ago",  text: "Drafted Mahindra §4.7 (Hybrid cloud architecture) — flagged 3 facts for SME confirmation." },
    ],
    requiredPermissions: ["presales.proposal.write"],
  },

  {
    id: "red_team",
    name: "Reviewer / Red-Team Agent",
    purpose: "Adversarial critique aligned to win themes and evaluation criteria for pink/red/gold reviews.",
    description:
      "Reads the in-flight proposal like a sceptical evaluator: scores against the rubric, calls out unsupported claims, weak win themes, missed shall-statements, jargon, and ghosting opportunities the team missed. Outputs a graded review packet with prioritised must-fixes.",
    trigger: "on_event",
    triggerDetail: "Pink / Red / Gold review milestone",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["pink_red_gold"] },
    tone: "warning",
    iconName: "TriangleAlert",
    activity7d: [1, 2, 0, 3, 2, 0, 0],
    accuracy30d: 0.84,
    overrideRate30d: 0.16,
    kpis: [
      { label: "Flaws caught pre-submission", value: "+47%", hint: "Vs reviewer-only baseline",            trend: "up" },
      { label: "Review yield",                  value: "31",   hint: "Avg actionable findings per review",  trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-rt-1", when: "Yesterday", text: "Red review on Aviva proposal — 28 findings, 6 must-fixes (mostly weak win-theme support)." },
      { id: "ra-rt-2", when: "3d ago",    text: "Pink review on Bank of Baroda — caught a missed shall-statement and 3 unsupported claims." },
    ],
    requiredPermissions: ["presales.review.run"],
  },

  {
    id: "compliance_sentinel",
    name: "Compliance Sentinel",
    purpose: "Continuously maps draft text back to requirements; flags gaps live during authoring.",
    description:
      "Runs continuously during drafting. For every requirement, evaluates whether the current draft covers it, partially covers it, or doesn't. Updates the compliance dashboard in real time; sends nudges to owners on the cusp of becoming red.",
    trigger: "continuous",
    triggerDetail: "Continuous (during drafting)",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["active_drafts"] },
    tone: "destructive",
    iconName: "ShieldCheck",
    activity7d: [44, 51, 49, 58, 56, 7, 9],
    accuracy30d: 0.93,
    overrideRate30d: 0.07,
    kpis: [
      { label: "Compliance score at submit", value: "99.4%", hint: "Reqs fully covered at gold review",      trend: "up" },
      { label: "Late-cycle compliance fires",  value: "−71%",  hint: "Vs prior-quarter baseline",              trend: "up" },
    ],
    recentActions: [
      { id: "ra-cs-1", when: "11m ago", text: "Bank of Baroda — covered 92% (227 / 247) reqs; 20 partial; 0 missing." },
      { id: "ra-cs-2", when: "44m ago", text: "Promoted Mahindra §6.3.4 to red — no on-task draft activity 96h." },
    ],
    requiredPermissions: ["presales.rfp.read"],
  },

  {
    id: "risk_identifier",
    name: "Risk Identifier",
    purpose: "Surfaces commercial and technical risks during solution + commercial drafting; suggests mitigations.",
    description:
      "Reads the solution and commercial drafts in lockstep. Flags risks (technical, delivery, commercial, IP, data, regulatory) and proposes mitigations with a recommendation on whether to disclose, mitigate, or accept. Keeps a live risk register that feeds delivery handoff if we win.",
    trigger: "continuous",
    triggerDetail: "During solution & commercial drafting",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["solution", "commercial"] },
    tone: "warning",
    iconName: "TriangleAlert",
    activity7d: [3, 5, 4, 7, 8, 0, 1],
    accuracy30d: 0.81,
    overrideRate30d: 0.19,
    kpis: [
      { label: "Risks logged / pursuit",    value: "14",     hint: "Avg, prior 30d",                        trend: "neutral" },
      { label: "Surprise risks post-award",   value: "−63%",  hint: "Vs prior-year baseline",                 trend: "up" },
    ],
    recentActions: [
      { id: "ra-ri-1", when: "1h ago",  text: "Flagged Aviva PI insurance ask of £10M as material — recommended adjust pricing or secure rider." },
      { id: "ra-ri-2", when: "Yesterday", text: "Caught a hidden 'unlimited liability for data breach' in Mahindra T&Cs — escalated to Legal." },
    ],
    requiredPermissions: ["presales.proposal.read", "presales.pricing.read"],
  },

  {
    id: "pricing_copilot",
    name: "Pricing Co-Pilot",
    purpose: "Win-probability-vs-price curve plus a competitor-price hypothesis.",
    description:
      "Helps the deal team understand the trade-off between price and probability of win using historical analogues, customer's prior spend, anchor of public market rates, and a structured competitor-price hypothesis. Outputs a recommended price band with rationale and dot-marks where each scenario lands on the win curve.",
    trigger: "on_event",
    triggerDetail: "Pricing workspace opened",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["pricing"] },
    tone: "brand-purple",
    iconName: "BarChart3",
    activity7d: [1, 2, 1, 4, 3, 0, 1],
    accuracy30d: 0.74,
    overrideRate30d: 0.26,
    kpis: [
      { label: "Margin maintained at target win rate", value: "26.4%", hint: "Avg gross margin on won deals",   trend: "up" },
      { label: "Price-win-curve usage",                  value: "82%",   hint: "Deals using the curve at pricing review", trend: "up" },
    ],
    recentActions: [
      { id: "ra-pc-1", when: "37m ago", text: "Mahindra — recommended ₹4.2-4.6 Cr band; hypothesised TCS at ₹3.8 Cr and Wipro at ₹4.4 Cr." },
      { id: "ra-pc-2", when: "2h ago",  text: "Aviva — flagged that current pricing implies 19% margin (below target); proposed scope trim." },
    ],
    requiredPermissions: ["presales.pricing.read"],
  },

  {
    id: "stakeholder_nudger",
    name: "Stakeholder Nudger",
    purpose: "Reminders, escalations, sentiment monitoring across the bid team.",
    description:
      "Keeps tasks on track without making humans the chasers. Smart-reminds owners at compounding intervals; escalates to capture lead at the right threshold; reads channel sentiment for early signs the team is stalling or unhappy.",
    trigger: "scheduled",
    triggerDetail: "Hourly + on milestone events",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_tasks"] },
    tone: "brand",
    iconName: "MessagesSquare",
    activity7d: [62, 71, 64, 78, 81, 9, 11],
    accuracy30d: 0.91,
    overrideRate30d: 0.09,
    kpis: [
      { label: "On-time task completion",  value: "94%", hint: "Up from 76% pre-agent", trend: "up" },
      { label: "Escalations per pursuit",    value: "2.1", hint: "Median, avoiding noise", trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-nu-1", when: "8m ago",  text: "Nudged Sandeep Mehta on Bank of Baroda §6.3.4 (now 96h overdue); escalated to capture lead." },
      { id: "ra-nu-2", when: "1h ago",  text: "Detected stalling sentiment on Aviva channel — flagged to PM and capture lead." },
    ],
    requiredPermissions: ["presales.pursuit.read", "presales.pursuit.write"],
  },

  {
    id: "submission_validator",
    name: "Submission Validator",
    purpose: "Final pre-flight: page limits, formats, forms, signatures, file naming.",
    description:
      "Pre-submission gate. Verifies page limits per section/exhibit, file formats, presence of required forms (CoI, references, financials), signatures, file-naming conventions, and submission-portal payload completeness. Blocks submission if a hard rule is violated; flags soft warnings for capture lead's call.",
    trigger: "on_event",
    triggerDetail: "Pre-submit gate",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_submissions"] },
    tone: "warning",
    iconName: "ShieldCheck",
    activity7d: [0, 1, 1, 2, 3, 0, 0],
    accuracy30d: 0.98,
    overrideRate30d: 0.02,
    kpis: [
      { label: "Submission rejections",      value: "0",     hint: "Target — last 4 quarters",                  trend: "up" },
      { label: "Blocked issues caught",        value: "39",    hint: "Hard violations stopped pre-submit, 30d",  trend: "neutral" },
    ],
    recentActions: [
      { id: "ra-sv-1", when: "Yesterday", text: "Blocked Aviva submit — Exhibit C exceeded the 8-page hard cap by 3 pages; auto-trimmed and re-validated after PM approval." },
      { id: "ra-sv-2", when: "3d ago",    text: "Caught a missing CoI form on Mahindra submit at T-90 minutes." },
    ],
    requiredPermissions: ["presales.submission.gate"],
  },

  {
    id: "question_tracker",
    name: "Question Tracker",
    purpose: "During evaluation Q&A — routes, drafts answers, tracks SLA.",
    description:
      "After submission, handles the evaluator-side Q&A: routes each inbound question to the right SME, drafts a response anchored in our submission, tracks the SLA clock, and notifies capture lead before any deadline slip.",
    trigger: "on_event",
    triggerDetail: "Evaluator question received",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["evaluation_qa"] },
    tone: "brand",
    iconName: "MessageCircle",
    activity7d: [4, 6, 5, 8, 7, 0, 1],
    accuracy30d: 0.87,
    overrideRate30d: 0.13,
    kpis: [
      { label: "Q&A turnaround",             value: "4.8 h", hint: "Median from receipt to dispatch", trend: "up" },
      { label: "Answers SME-accepted ≥ 80%",   value: "73%",   hint: "First-pass draft quality",        trend: "up" },
    ],
    recentActions: [
      { id: "ra-qt-1", when: "21m ago", text: "Routed Bank of Baroda Q-14 (production architecture) to S Hegde with a 380-word draft answer." },
      { id: "ra-qt-2", when: "1h ago",  text: "Flagged Aviva Q-9 SLA — 4h remaining, draft not yet started; nudged owner." },
    ],
    requiredPermissions: ["presales.qna.act"],
  },

  {
    id: "orals_prep",
    name: "Orals Prep Agent",
    purpose: "Drafts the presentation, briefing book, and Q&A prep when shortlisted.",
    description:
      "Once shortlisted, assembles the orals pack: slide draft tuned to evaluator hot buttons, briefing book with key facts and risks, anticipated Q&A with model answers, and prep prompts for the speakers.",
    trigger: "on_event",
    triggerDetail: "On shortlist confirmed",
    defaultStatus: true,
    defaultAutonomy: "suggest",
    defaultScope: { cohorts: ["orals"] },
    tone: "brand-purple",
    iconName: "GraduationCap",
    activity7d: [0, 1, 0, 2, 1, 0, 0],
    accuracy30d: 0.79,
    overrideRate30d: 0.21,
    kpis: [
      { label: "Win rate at orals stage",     value: "+11pp", hint: "Vs orals-without-prep baseline",          trend: "up" },
      { label: "Orals-day surprises",           value: "−58%",  hint: "Questions team wasn't briefed for",       trend: "up" },
    ],
    recentActions: [
      { id: "ra-op-1", when: "Yesterday", text: "Drafted Mahindra orals pack — 18 slides, 27-page briefing book, 41 anticipated Q&A pairs." },
      { id: "ra-op-2", when: "5d ago",    text: "Updated Aviva orals deck after CFO change — repositioned commercial framing." },
    ],
    requiredPermissions: ["presales.proposal.write"],
  },

  {
    id: "win_loss_synth",
    name: "Win/Loss Synthesizer",
    purpose: "Conducts the debrief, categorises drivers, surfaces lessons for the library.",
    description:
      "On decision (win or loss), runs the debrief: interviews capture/sales/SME via Slack, pulls the customer's evaluation memo where available, categorises drivers across pricing, fit, relationship, execution, content quality. Writes the debrief and feeds the Knowledge Curator with reusable wins and red-flag patterns.",
    trigger: "on_event",
    triggerDetail: "On decision received",
    defaultStatus: true,
    defaultAutonomy: "act_with_confirm",
    defaultScope: { cohorts: ["all_decisions"] },
    tone: "brand-teal",
    iconName: "Shuffle",
    activity7d: [1, 2, 0, 1, 2, 0, 0],
    accuracy30d: 0.85,
    overrideRate30d: 0.15,
    kpis: [
      { label: "Debriefs completed",        value: "98%",   hint: "Of decisions in last 30d",                  trend: "up" },
      { label: "Drivers reused in next bid", value: "44%",   hint: "Findings that influenced a subsequent pursuit", trend: "up" },
    ],
    recentActions: [
      { id: "ra-wl-1", when: "Yesterday", text: "Closed DBS debrief — won, three drivers: industry references, price aggressiveness, named team." },
      { id: "ra-wl-2", when: "4d ago",    text: "Closed Capgemini-loss debrief — incumbent advantage and a missed evaluation criterion." },
    ],
    requiredPermissions: ["presales.debrief.write"],
  },

  {
    id: "knowledge_curator",
    name: "Knowledge Curator",
    purpose: "Tags reusable content from closed pursuits, keeps the library fresh.",
    description:
      "Post-decision, picks the high-reuse content (case studies, win themes, qualifications, references), tags with provenance and freshness, and pushes to the proposal library. Flags content nearing stale on a rolling basis so SMEs refresh before it bites a future bid.",
    trigger: "on_event",
    triggerDetail: "On pursuit closed",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["closed_pursuits"] },
    tone: "brand-teal",
    iconName: "Library",
    activity7d: [4, 5, 3, 6, 7, 1, 1],
    accuracy30d: 0.91,
    overrideRate30d: 0.09,
    kpis: [
      { label: "Library freshness",         value: "92%",   hint: "Entries < 9 months old (target: 85%+)", trend: "up" },
      { label: "Content reuse %",             value: "63%",   hint: "Cross-references library on next pursuit", trend: "up" },
    ],
    recentActions: [
      { id: "ra-kc-1", when: "Yesterday", text: "Promoted DBS wealth-management case study (won 14 May) to gold library; tagged 6 themes." },
      { id: "ra-kc-2", when: "3d ago",    text: "Flagged 14 entries as stale (no refresh in 12+ months); queued SME owners." },
    ],
    requiredPermissions: ["presales.library.write"],
  },

  {
    id: "status_drafter",
    name: "Status Drafter",
    purpose: "Daily and on-event status for exec sponsor and Sales Lead.",
    description:
      "Saves the capture lead from writing the same status note every day. Composes a tight exec-facing status from the underlying data: compliance %, risk register diff, where the ball is, what's on the critical path, what the exec sponsor needs to unblock. Posts to channel and email at the chosen cadence.",
    trigger: "scheduled",
    triggerDetail: "Daily 17:00 IST + on milestone",
    defaultStatus: true,
    defaultAutonomy: "autonomous",
    defaultScope: { cohorts: ["all_active_pursuits"] },
    tone: "brand",
    iconName: "Captions",
    activity7d: [6, 7, 6, 7, 7, 1, 1],
    accuracy30d: 0.90,
    overrideRate30d: 0.10,
    kpis: [
      { label: "Exec time saved",      value: "~3 h / wk", hint: "Vs hand-written daily status", trend: "up" },
      { label: "Status read rate",      value: "84%",      hint: "Recipients opening status notes", trend: "up" },
    ],
    recentActions: [
      { id: "ra-sd-1", when: "Today 17:00", text: "Posted daily across 6 active pursuits — 2 with red items requiring sponsor attention." },
      { id: "ra-sd-2", when: "Yesterday",   text: "Special event status — Aviva CFO change, sentiment shift on capture channel." },
    ],
    requiredPermissions: ["presales.pursuit.read"],
  },
];

/* ───────────────────────── Sample decisions ───────────────────────── */

const DECISIONS: AgentDecision[] = [
  {
    id: "pd-1",
    agentId: "rfp_decomposer",
    whenISO: "2026-05-11T03:47:00.000Z",
    whenLabel: "11 May, 09:17",
    summary: "Decomposed Bank of Baroda RFP — 247 shall-statements, 3 mandatory forms, 11 May submission.",
    outcome: "executed",
    confidence: 96,
    recordId: "PRS-BOB-001",
    recordLabel: "Bank of Baroda — Fraud Analytics RFP",
  },
  {
    id: "pd-2",
    agentId: "bid_no_bid",
    whenISO: "2026-05-11T07:12:00.000Z",
    whenLabel: "11 May, 12:42",
    summary: "Recommended Bid on Mahindra RFP — fit 78%, win-prob 41%, 3 strong analogues.",
    outcome: "pending_review",
    confidence: 81,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-3",
    agentId: "bid_no_bid",
    whenISO: "2026-05-10T10:30:00.000Z",
    whenLabel: "Yesterday, 16:00",
    summary: "Recommended No-Bid on Maersk Ops Platform — no operational depth in shipping; CoP avoided ₹38L.",
    outcome: "executed",
    confidence: 88,
    recordId: "PRS-MAERSK-002",
    recordLabel: "Maersk — Ops Platform Refresh",
  },
  {
    id: "pd-4",
    agentId: "compliance_matrix_builder",
    whenISO: "2026-05-11T04:02:00.000Z",
    whenLabel: "11 May, 09:32",
    summary: "Built compliance matrix (247 reqs); auto-tagged 219 owners, 28 queued for SME review.",
    outcome: "executed",
    confidence: 94,
    recordId: "PRS-BOB-001",
    recordLabel: "Bank of Baroda — Fraud Analytics RFP",
  },
  {
    id: "pd-5",
    agentId: "compliance_sentinel",
    whenISO: "2026-05-12T06:11:00.000Z",
    whenLabel: "Today, 11:41",
    summary: "Promoted Mahindra §6.3.4 to RED — no draft activity in 96h; nudged owner and capture lead.",
    outcome: "executed",
    confidence: 97,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-6",
    agentId: "capture_copilot",
    whenISO: "2026-05-11T11:30:00.000Z",
    whenLabel: "11 May, 17:00",
    summary: "Drafted Mahindra capture plan v1 — 7 win themes, 4 ghosting moves.",
    outcome: "suggested",
    confidence: 78,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-7",
    agentId: "customer_intel",
    whenISO: "2026-05-12T06:46:00.000Z",
    whenLabel: "Today, 12:16",
    summary: "Aviva — CFO resigned. Capture lead notified; brief updated.",
    outcome: "executed",
    confidence: 92,
    recordId: "PRS-AVIVA-001",
    recordLabel: "Aviva — Claims Analytics Refresh",
  },
  {
    id: "pd-8",
    agentId: "competitor_intel",
    whenISO: "2026-05-11T13:00:00.000Z",
    whenLabel: "11 May, 18:30",
    summary: "Mahindra — anticipates TCS, Wipro, and Capgemini incumbent extension.",
    outcome: "suggested",
    confidence: 76,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-9",
    agentId: "question_drafter",
    whenISO: "2026-05-11T16:15:00.000Z",
    whenLabel: "11 May, 21:45",
    summary: "Drafted 11 clarifying questions on Mahindra RFP; capture lead approved 9.",
    outcome: "overridden",
    confidence: 83,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-10",
    agentId: "content_recommender",
    whenISO: "2026-05-12T06:38:00.000Z",
    whenLabel: "Today, 12:08",
    summary: "Recommended 3 fraud-detection case studies for Bank of Baroda §3.2.",
    outcome: "executed",
    confidence: 89,
    recordId: "PRS-BOB-001",
    recordLabel: "Bank of Baroda — Fraud Analytics RFP",
  },
  {
    id: "pd-11",
    agentId: "first_draft_author",
    whenISO: "2026-05-12T06:02:00.000Z",
    whenLabel: "Today, 11:32",
    summary: "Seeded draft for Bank of Baroda §3.2 (Fraud detection approach) — 1,180 words, 6 citations.",
    outcome: "pending_review",
    confidence: 79,
    recordId: "PRS-BOB-001",
    recordLabel: "Bank of Baroda — Fraud Analytics RFP",
  },
  {
    id: "pd-12",
    agentId: "red_team",
    whenISO: "2026-05-10T13:00:00.000Z",
    whenLabel: "Yesterday, 18:30",
    summary: "Red review on Aviva — 28 findings, 6 must-fixes (weak win-theme support, 1 unsupported claim).",
    outcome: "executed",
    confidence: 84,
    recordId: "PRS-AVIVA-001",
    recordLabel: "Aviva — Claims Analytics Refresh",
  },
  {
    id: "pd-13",
    agentId: "risk_identifier",
    whenISO: "2026-05-12T05:42:00.000Z",
    whenLabel: "Today, 11:12",
    summary: "Aviva PI insurance ask of £10M flagged as material — recommended price adjust or rider.",
    outcome: "pending_review",
    confidence: 81,
    recordId: "PRS-AVIVA-001",
    recordLabel: "Aviva — Claims Analytics Refresh",
  },
  {
    id: "pd-14",
    agentId: "pricing_copilot",
    whenISO: "2026-05-12T06:09:00.000Z",
    whenLabel: "Today, 11:39",
    summary: "Mahindra — recommended ₹4.2-4.6 Cr; hypothesised TCS ₹3.8 Cr, Wipro ₹4.4 Cr; CPI capped at 5%.",
    outcome: "pending_review",
    confidence: 74,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-15",
    agentId: "stakeholder_nudger",
    whenISO: "2026-05-12T06:38:00.000Z",
    whenLabel: "Today, 12:08",
    summary: "Nudged Sandeep Mehta on §6.3.4 (96h overdue) and escalated to capture lead.",
    outcome: "executed",
    confidence: 95,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-16",
    agentId: "submission_validator",
    whenISO: "2026-05-10T16:15:00.000Z",
    whenLabel: "Yesterday, 21:45",
    summary: "BLOCKED Aviva submit — Exhibit C exceeded 8-page cap by 3; auto-trimmed after PM approval.",
    outcome: "executed",
    confidence: 99,
    recordId: "PRS-AVIVA-001",
    recordLabel: "Aviva — Claims Analytics Refresh",
  },
  {
    id: "pd-17",
    agentId: "question_tracker",
    whenISO: "2026-05-12T06:31:00.000Z",
    whenLabel: "Today, 12:01",
    summary: "Routed Bank of Baroda Q-14 (production architecture) to S Hegde with a 380-word draft answer.",
    outcome: "suggested",
    confidence: 88,
    recordId: "PRS-BOB-001",
    recordLabel: "Bank of Baroda — Fraud Analytics RFP",
  },
  {
    id: "pd-18",
    agentId: "orals_prep",
    whenISO: "2026-05-10T11:00:00.000Z",
    whenLabel: "Yesterday, 16:30",
    summary: "Drafted Mahindra orals pack — 18 slides, briefing book, 41 anticipated Q&A pairs.",
    outcome: "suggested",
    confidence: 80,
    recordId: "PRS-MM-001",
    recordLabel: "Mahindra — Group Cloud Migration RFP",
  },
  {
    id: "pd-19",
    agentId: "win_loss_synth",
    whenISO: "2026-05-10T10:00:00.000Z",
    whenLabel: "Yesterday, 15:30",
    summary: "Closed DBS debrief — won, drivers: industry refs, price aggressiveness, named team.",
    outcome: "executed",
    confidence: 87,
    recordId: "PRS-DBS-002",
    recordLabel: "DBS — Wealth Mgmt Phase 2",
  },
  {
    id: "pd-20",
    agentId: "knowledge_curator",
    whenISO: "2026-05-10T12:00:00.000Z",
    whenLabel: "Yesterday, 17:30",
    summary: "Promoted DBS wealth-mgmt case study to gold library; tagged 6 themes.",
    outcome: "executed",
    confidence: 93,
    recordId: "PRS-DBS-002",
    recordLabel: "DBS — Wealth Mgmt Phase 2",
  },
  {
    id: "pd-21",
    agentId: "status_drafter",
    whenISO: "2026-05-12T11:30:00.000Z",
    whenLabel: "Today, 17:00",
    summary: "Posted daily status across 6 pursuits; 2 reds require sponsor attention.",
    outcome: "executed",
    confidence: 91,
    recordId: undefined,
    recordLabel: "All active pursuits",
  },
];

/* ───────────────────────── Decision traces ───────────────────────── */

const TRACES: Record<string, DecisionTrace> = {
  /* RFP Decomposer — full pipeline on a real RFP. */
  "pd-1": {
    decisionId: "pd-1",
    input: [
      { label: "RFP file",          value: "BoB-RFP-FRAUD-2026-004.pdf (84 pages)" },
      { label: "Customer",          value: "Bank of Baroda — Procurement (Mumbai)" },
      { label: "Channel",           value: "BoB e-procurement portal → automated webhook" },
      { label: "Pursuit id",        value: "PRS-BOB-001" },
      { label: "Submission deadline", value: "2026-05-21 17:00 IST" },
    ],
    tools: [
      { id: "t-1", name: "PDF text + layout extraction",       whenLabel: "+0s",   summary: "Extracted text + table structure across 84 pages.",      kind: "calc",        result: "84 pages · 247 numbered clauses · 11 tables" },
      { id: "t-2", name: "Shall-statement detector",           whenLabel: "+12s",  summary: "Pattern-matched normative language across all sections.", kind: "model_call",  result: "247 shall-statements identified (98% precision on held-out)" },
      { id: "t-3", name: "Evaluation criteria classifier",     whenLabel: "+19s",  summary: "Tagged §7 weighted scoring (Technical 60 / Commercial 40).", kind: "model_call",  result: "Technical 60% (3 sub-criteria); Commercial 40% (2 sub-criteria)" },
      { id: "t-4", name: "Form & attachment registry",          whenLabel: "+24s",  summary: "Catalogued mandatory annexures.",                          kind: "calc",        result: "3 forms: CoI declaration, Financial capacity, Past performance (last 5y)" },
      { id: "t-5", name: "Date & SLA extractor",                whenLabel: "+29s",  summary: "Extracted deadlines, Q&A window, evaluation timeline.",     kind: "calc",        result: "Q&A window 12-14 May · Submit 21 May 17:00 IST · Shortlist 5 Jun" },
      { id: "t-6", name: "Ambiguity detector",                  whenLabel: "+33s",  summary: "Flagged statements where intent is unclear.",               kind: "model_call",  result: "6 ambiguities — queued for Question Drafter" },
      { id: "t-7", name: "Page-limit + format guardrails",       whenLabel: "+37s",  summary: "Read submission rules from §1.4 + Schedule C.",             kind: "calc",        result: "Main response: 80 pages · Exhibit C: 8 pages · PDF only · A4 portrait" },
      { id: "t-8", name: "Compliance Matrix handoff",            whenLabel: "+41s", summary: "Posted decomposition to Compliance Matrix Builder.",        kind: "agent_call",  result: "Builder accepted; matrix online at PRS-BOB-001/matrix" },
    ],
    policyRules: [
      { id: "r-1", label: "Customer is on tier-A list — full pursuit lifecycle applies",  outcome: "pass" },
      { id: "r-2", label: "RFP is < 30 days to submit — fast-track lane enabled",         outcome: "warn" },
      { id: "r-3", label: "No conflict-of-interest with existing BoB engagements",        outcome: "pass" },
    ],
    reasoning: [
      "BoB e-procurement webhook delivered the RFP at 09:14 IST.",
      "Decomposition completed in 11 minutes — within target SLA (15 minutes).",
      "247 shall-statements is consistent with a banking analytics RFP of this scope (mean 240, σ 28).",
      "Six ambiguous statements were detected and routed to Question Drafter for the 12-14 May Q&A window.",
      "Posted compliance matrix skeleton to Compliance Matrix Builder for owner-tagging; capture lead notified.",
    ],
    output: {
      pursuit: "PRS-BOB-001",
      requirements: 247,
      forms: 3,
      ambiguities: 6,
      evaluationCriteria: { Technical: 60, Commercial: 40 },
      pageLimits: { main: 80, exhibitC: 8 },
      timeline: {
        decomposeISO: "2026-05-11T03:47:00.000Z",
        qaWindow: "2026-05-12 — 2026-05-14",
        submitISO: "2026-05-21T11:30:00.000Z",
        shortlistISO: "2026-06-05",
      },
      handoff: "Compliance Matrix Builder",
    },
  },

  /* Pricing Co-Pilot — recommended price band and competitor hypothesis. */
  "pd-14": {
    decisionId: "pd-14",
    input: [
      { label: "Pursuit id",          value: "PRS-MM-001" },
      { label: "Customer",            value: "Mahindra & Mahindra — Group IT" },
      { label: "Scope",               value: "Cloud migration + managed services, 24 months" },
      { label: "Our cost (rolled)",   value: "₹3.1 Cr (delivery + overhead, 24m)" },
      { label: "Target gross margin",  value: "26% — corporate guidance for FY26" },
    ],
    tools: [
      { id: "t-1", name: "Analogue pursuit retrieval",          whenLabel: "+0s",   summary: "Pulled 7 most similar pursuits from last 24 months.",   kind: "data_fetch",  result: "7 analogues — 4 won, 3 lost · median price ₹4.3 Cr · σ ₹0.6 Cr" },
      { id: "t-2", name: "Win-probability model",                whenLabel: "+4s",   summary: "Fitted price vs win-prob curve on the analogue set.",   kind: "model_call",  result: "Curve: ₹3.8 Cr → 58% · ₹4.2 Cr → 47% · ₹4.6 Cr → 36% · ₹5.0 Cr → 24%" },
      { id: "t-3", name: "Competitor price hypothesis",          whenLabel: "+9s",   summary: "Composed competitor-side price hypotheses.",            kind: "model_call",  result: "TCS likely ₹3.7-3.9 Cr (aggressive, incumbent-adjacent); Wipro ₹4.3-4.5 Cr (balanced); Capgemini ₹4.6-4.8 Cr (incumbent extension)" },
      { id: "t-4", name: "Margin sanity check",                  whenLabel: "+11s",  summary: "Validated margin at each band against cost roll-up.",   kind: "calc",        result: "₹4.2 Cr → 26.2% · ₹4.6 Cr → 32.6% · ₹3.8 Cr → 18.4% (below target)" },
      { id: "t-5", name: "Customer prior-spend lookup",           whenLabel: "+13s",  summary: "Mahindra group prior 3y average tech-services spend.", kind: "data_fetch",  result: "₹220 Cr / yr · this engagement is < 1% of budget · low price-anchor risk" },
      { id: "t-6", name: "Risk Identifier check",                 whenLabel: "+16s",  summary: "Cross-checked with risk register.",                     kind: "agent_call",  result: "No commercial blockers; flagged 'data residency penalty clause' to monitor" },
    ],
    policyRules: [
      { id: "r-1", label: "Recommendation must keep margin ≥ corporate target (26%)", outcome: "pass" },
      { id: "r-2", label: "Aggressive pricing (< target margin) requires CFO sign-off", outcome: "pass" },
      { id: "r-3", label: "Price band must show ≥ 35% win-prob at recommended price",   outcome: "pass" },
    ],
    reasoning: [
      "Cost-floor at our target margin sits at ₹4.2 Cr; the curve shows 47% win-prob at that point.",
      "₹4.6 Cr is the upper band — margin 32.6%, win-prob 36%. The 11pp margin gain vs 11pp win-prob loss is roughly value-neutral.",
      "Below ₹4.2 Cr we drop below margin guidance, which requires CFO sign-off and dilutes the corporate FY26 plan.",
      "TCS is the price-anchor risk — historical pattern shows TCS underbids by ~7% on Mahindra engagements but loses on solution depth in 60% of cases.",
      "Recommendation: ₹4.2-4.6 Cr band, defending value rather than chasing price. Suggest a tiered-scope option to give Mahindra a 'lower price + lower scope' alternative that still hits margin.",
    ],
    output: {
      pursuit: "PRS-MM-001",
      recommendedBand: { lowINR: 42_000_000, highINR: 46_000_000 },
      atLowEnd:  { priceINR: 42_000_000, winProb: 0.47, marginPct: 26.2 },
      atHighEnd: { priceINR: 46_000_000, winProb: 0.36, marginPct: 32.6 },
      competitorHypothesis: {
        TCS:        { lowINR: 37_000_000, highINR: 39_000_000, note: "Aggressive, incumbent-adjacent" },
        Wipro:      { lowINR: 43_000_000, highINR: 45_000_000, note: "Balanced — matches our recommended floor" },
        Capgemini:  { lowINR: 46_000_000, highINR: 48_000_000, note: "Incumbent extension; price discipline" },
      },
      mitigations: [
        "Tiered-scope option (light + standard + premium) to give Mahindra a sub-₹4 Cr door without breaching margin guidance",
        "Defend value on solution depth + named team — TCS historically underbids 7% but loses on depth",
        "Quote in INR, with CPI escalator capped at 5% (per playbook)",
      ],
      handoff: "Pursuit lead + CFO for final sign-off",
    },
  },
};

export const PRESALES_AGENT_REGISTRY: AgentRegistry = {
  module: "presales",
  agents: AGENTS,
  decisions: DECISIONS,
  traces: TRACES,
};
